# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_code', models.CharField(max_length=255, unique=True)),
                ('continent_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owid_name', models.CharField(max_length=255, unique=True)),
                ('owid_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('iso_alpha2', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('iso_alpha3', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('imf_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('cow_letter', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cow_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('unctad_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('marc_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ncd_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('kansas_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('penn_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('continent', models.ForeignKey(db_column='continent', on_delete=django.db.models.deletion.CASCADE, to='country_name_tool.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, unique=True)),
                ('owid_country', models.ForeignKey(db_column='owid_country', on_delete=django.db.models.deletion.CASCADE, to='country_name_tool.CountryData')),
            ],
        ),
    ]
