# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_name_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='continent',
            field=models.ForeignKey(db_column='continent', null=True, on_delete=django.db.models.deletion.CASCADE, to='country_name_tool.Continent'),
        ),
    ]
