# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 13:02
from __future__ import unicode_literals

from django.db import migrations


def load_continents(apps, schema_editor):
    continent = apps.get_model("country_name_tool", "Continent")
    newcontinents = [['NA', 'North America'], ['AS', 'Asia'], ['AF', 'Africa'], ['EU', 'Europe'], ['SA', 'South America'], ['OC', 'Oceania'], ['AN', 'Antarctica']]
    for each in newcontinents:
        toinsert = continent(continent_code=each[0], continent_name=each[1])
        toinsert.save()


class Migration(migrations.Migration):

    dependencies = [
        ('country_name_tool', '0002_auto_20170523_1825'),
    ]

    operations = [
        migrations.RunPython(load_continents)
    ]
