# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_name_tool', '0003_auto_20170609_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydata',
            name='owid_code',
        ),
    ]
