#!/bin/bash
#
#  deploy-content-preview
#
#  Manually deploy the staging bakedSite to Cloudflare Pages in preview mode
#
#  See /functions/README.md > "Testing on Fondation staging sites vs Cloudflare
#  previews" for the rationale behind this script.
#
#  USAGE
#
#  - $ yarn deployContentPreview (default, deploys to
#    https://[YOUR_CURRENT_GIT_BRANCH].owid.pages.dev)
#  - $ PREVIEW_BRANCH=[PREVIEW_BRANCH] yarn deployContentPreview (deploys to
#    https://[PREVIEW_BRANCH].owid.pages.dev)

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
HOST="staging-site-$GIT_BRANCH"

PREVIEW_BRANCH=${PREVIEW_BRANCH:-$GIT_BRANCH}

echo "This script has been replaced. Please use the following command from the ops repository:"
echo "BUILDKITE_BRANCH=$PREVIEW_BRANCH bash templates/owid-site-staging/deploy-content-preview.sh $HOST"

echo ""
echo "Note: This process has been fully automated on staging servers after pushing commits."
echo "You can still use this script manually, but it's only useful if you're deploying to a different domain than 'https://$PREVIEW_BRANCH.owid.pages.dev/'"
