// Real-world component usage mined from the production gdocs DB.
// GENERATED by scripts/mine-component-examples.ts — do not edit by hand.
// Counts are occurrences across published gdocs at mining time; examples
// carry provenance (slug + gdoc type) and were validated to round-trip
// through the vendored XHTML serializer/parser. Data only — consumed by
// catalog.ts and (later) a component gallery.

import type { ComponentUsage } from "./componentCatalog.js";

export const componentExamples: Record<string, ComponentUsage> = {
  "additional-charts": {
    count: 71,
    examples: [
      {
        slug: "sdgs/peace-justice-institutions",
        gdocType: "article",
        xhtml:
          '<additional-charts>\n  <item>\n    <a href="https://ourworldindata.org/grapher/number-of-homicides-unodc">Number of homicides</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/homicide-rate-1990-vs-2019">Homicide rate in 1990 vs. 2020</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/female-homicide-rate">Female homicide rate</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/male-homicide-rate">Male homicide rate</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/homicide-rate-by-age">Homicide rate by age of the victim</a>\n  </item>\n</additional-charts>',
      },
      {
        slug: "sdgs/good-health-wellbeing",
        gdocType: "article",
        xhtml:
          '<additional-charts>\n  <item>\n    <a href="https://ourworldindata.org/grapher/death-rates-from-ambient-particulate-air-pollution?tab=map">Mortality rate from ambient particulate air pollution</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/absolute-number-of-deaths-from-outdoor-air-pollution">Number of deaths from outdoor air pollution</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/death-rate-by-source-from-indoor-air-pollution">Mortality rate from indoor air pollution</a>\n  </item>\n  <item>\n    <a href="https://ourworldindata.org/grapher/absolute-number-of-deaths-from-household-air-pollution">Number of deaths from indoor air pollution</a>\n  </item>\n</additional-charts>',
      },
    ],
  },
  align: {
    count: 1,
    examples: [
      {
        slug: "sdgs",
        gdocType: "article",
        xhtml:
          '<align alignment="center">\n  <heading level="2">The 17 Sustainable Development Goals</heading>\n  <heading level="3">Click on a Goal below to see interactive charts for available indicators</heading>\n</align>',
      },
    ],
  },
  "all-charts": {
    count: 109,
    examples: [
      {
        slug: "coronavirus",
        gdocType: "topic-page",
        xhtml:
          '<all-charts heading="Interactive Charts on COVID-19">\n  <top url="https://ourworldindata.org/grapher/excess-mortality-raw-death-count-single-series"/>\n  <top url="https://ourworldindata.org/grapher/excess-mortality-p-scores-projected-baseline-by-age"/>\n  <top url="https://ourworldindata.org/grapher/excess-deaths-cumulative-economist-single-entity"/>\n  <top url="https://ourworldindata.org/grapher/covid-variants-area"/>\n  <top url="https://ourworldindata.org/grapher/share-people-fully-vaccinated-covid"/>\n  <top url="https://ourworldindata.org/grapher/daily-covid-vaccination-doses-per-capita"/>\n  <top url="https://ourworldindata.org/grapher/daily-cases-covid-region"/>\n  <top url="https://ourworldindata.org/grapher/daily-new-estimated-infections-of-covid-19"/>\n  <top url="https://ourworldindata.org/grapher/weekly-hospital-admissions-covid-per-million"/>\n  <top url="https://ourworldindata.org/grapher/daily-covid-deaths-region"/>\n</all-charts>',
      },
      {
        slug: "causes-of-death",
        gdocType: "topic-page",
        xhtml:
          '<all-charts heading="Interactive Charts on Causes of Death">\n  <top url="https://ourworldindata.org/grapher/annual-number-of-deaths-by-cause"/>\n  <top url="https://ourworldindata.org/grapher/share-of-deaths-from-major-causes"/>\n  <top url="https://ourworldindata.org/grapher/age-standardized-deaths-from-all-causes"/>\n  <top url="https://ourworldindata.org/grapher/death-rate-by-cause-who-mdb"/>\n  <top url="https://ourworldindata.org/grapher/cancer-death-rate-who-mdb"/>\n  <top url="https://ourworldindata.org/grapher/cardiovascular-disease-death-rates-who-mdb"/>\n  <top url="https://ourworldindata.org/grapher/respiratory-infection-death-rate-who-mdb"/>\n  <top url="https://ourworldindata.org/grapher/infectious-and-parasitic-diseases-death-rate-who-mdb"/>\n  <top url="https://ourworldindata.org/grapher/death-rate-from-communicable-vs-non-communicable-diseases"/>\n</all-charts>',
      },
    ],
  },
  aside: {
    count: 89,
    examples: [
      {
        slug: "demographic-health-surveys-risk",
        gdocType: "article",
        xhtml:
          '<aside position="right">\n  <a href="https://ourworldindata.org/excess-mortality-covid">Excess deaths</a> are the number of deaths during a crisis beyond what we would expect under normal conditions. This measure captures both direct and indirect impacts, including unreported COVID-19 deaths and those caused by broader disruptions.\n</aside>',
      },
      {
        slug: "2024-living-planet-index",
        gdocType: "article",
        xhtml:
          '<aside position="right">You can see the share of populations that are strongly or moderately increasing and decreasing \n  <a href="https://ourworldindata.org/grapher/share-of-populations-increasing-stable-or-decreasing-in-the-living-planet-index">in this chart</a>.\n</aside>',
      },
    ],
  },
  "bespoke-component": {
    count: 21,
    examples: [
      {
        slug: "south-koreas-population-is-set-to-shrink-what-would-it-take-to-stop-the-decline",
        gdocType: "article",
        xhtml:
          '<bespoke-component bundle="demography" variant="simulation" size="wide" config-region="South Korea" config-focusParameter="netMigrationRate" config-hideEntitySelector="true" config-hidePopulationPyramid="true" config-netMigrationRateAssumptions="0.9,8.7,8.7"/>',
      },
      {
        slug: "five-million-children-die-every-year-what-do-they-die-from",
        gdocType: "article",
        xhtml:
          '<bespoke-component bundle="causes-of-death" variant="treemap" size="wide" config-year="2023" config-region="United Kingdom" config-ageGroup="Children under 5" config-hideControls="true"/>',
      },
    ],
  },
  blockquote: {
    count: 50,
    examples: [
      {
        slug: "global-decline-fertility-rate",
        gdocType: "article",
        xhtml:
          '<blockquote citation="George Alter and Gregory Clark">\n  <text>In Spain, for example, regional differences in fertility followed the boundaries between areas that spoke dialects of Spanish or different languages, such as Basque or Catalan (Leasure, 1963). In France fertility decline was later in Breton-speaking départements. Belgium, divided into Flemish- and French-speaking regions, shows most clearly the importance of linguistic borders. Lesthaeghe (1977) studied seventy Walloon villages matched to neighboring Flemish villages with identical economic conditions. Fertility fell first in the Walloon village in sixty-two of the pairs, and the fertility decline began twenty years earlier on average in the Walloon village (Lesthaeghe, 1977). Flemish couples in the city of Leuven were more likely to have small families if a migrant from Wallonia lived nearby (Van Bavel, 2004).</text>\n</blockquote>',
      },
      {
        slug: "does-population-growth-lead-to-hunger-and-famine",
        gdocType: "article",
        xhtml:
          '<blockquote citation="British environmentalist Sir Jonathon Porrit, 11/07/2011">\n  <text>\n    <i>It’s no good blaming climate change or food shortages or political corruption. Sorry to be neo-Malthusian about it, but </i>\n    <b>\n      <i>continuing population growth in this region makes periodic famine unavoidable</i>\n    </b>\n    <i>... Many of the children saved by the money raised over the next few weeks will inevitably be back again in similar feeding centres with their own children in a few years time</i>\n    <ref url="#note-1">\n      <sup>1</sup>\n    </ref>\n    <i>.</i>\n  </text>\n</blockquote>',
      },
    ],
  },
  callout: {
    count: 413,
    examples: [
      {
        slug: "end-progress-extreme-poverty",
        gdocType: "article",
        xhtml:
          '<callout icon="info" title="Note on the earlier version of this article">\n  <text>This is an update of an article that I published in May 2019 on Our World in Data, titled “\n    <a href="https://web.archive.org/web/20190513154042/https://ourworldindata.org/extreme-poverty-projections">As the world’s poorest economies are stagnating, half a billion are expected to be in extreme poverty in 2030</a>”.\n  </text>\n  <text>Based on even earlier projections, I also made this a central point of my presentation to the UN back in 2018, for which you can find my slides \n    <a href="https://ourworldindata.org/max-un-slides">here</a>.\n  </text>\n</callout>',
      },
      {
        slug: "does-the-news-reflect-what-we-die-from",
        gdocType: "article",
        xhtml:
          '<callout icon="info" title="Correction note">\n  <text>This article was initially published on October 6, 2025, and was updated on October 9. This update corrected an error, whereby “Drug and overdose” deaths were also included within the US CDC category of “Accidents”. This meant that they were double-counted. We have corrected this, and the change made only a small difference to the final numbers. The relative share of deaths from accidents changed from 9.5% to 7.8%, and the share of other causes increased slightly. We thank Karl Pettersson for flagging this.</text>\n</callout>',
      },
    ],
  },
  chart: {
    count: 2305,
    examples: [
      {
        slug: "environmental-impacts-of-food",
        gdocType: "topic-page",
        xhtml:
          '<chart url="https://ourworldindata.org/explorers/food-footprints?facet=none&amp;Commodity+or+Specific+Food+Product=Commodity&amp;Environmental+Impact=Carbon+footprint&amp;Kilogram+%2F+Protein+%2F+Calories=Per+kilogram&amp;By+stage+of+supply+chain=false&amp;country=Bananas~Beef+%28beef+herd%29~Beef+%28dairy+herd%29~Cheese~Eggs~Lamb+%26+Mutton~Milk~Maize~Nuts~Pig+Meat~Peas~Potatoes~Poultry+Meat~Rice~Tomatoes~Wheat+%26+Rye~Tofu+%28soybeans%29~Prawns+%28farmed%29&amp;hideControls=false"/>',
      },
      {
        slug: "countries-critical-minerals-needed-energy-transition",
        gdocType: "article",
        xhtml:
          '<chart url="https://ourworldindata.org/explorers/minerals?time=latest&amp;facet=none&amp;country=CHL~DZA~ARG~ARM~ZMB~OWID_GFR~VNM~UZB~UGA~TUR~TZA~TJK~SWE~ESP~SVK~SAU~ROU~PRT~PER~PNG~PAN~PAK~Other~OMN~PRK~NIC~NZL~NAM~MOZ~MNG~MEX~MRT~MYS~LAO~KGZ~KEN~KAZ~ITA~ISR~IRL~IRN~HUN~HND~HTI~DEU~GEO~ERI~ECU~COD~CYP~COG~BGR~BWA~BOL~AZE~IDN~CHN~JPN~CAN~RUS~AUS~FIN~NOR~NCL~BRA&amp;Mineral=Nickel&amp;Metric=Production&amp;Type=Processing&amp;Share+of+global=true&amp;hideControls=true&amp;tab=discrete-bar"/>',
      },
    ],
  },
  "chart-story": {
    count: 87,
    examples: [
      {
        slug: "sdgs/life-on-land",
        gdocType: "article",
        xhtml:
          '<chart-story>\n  <item>\n    <narrative>Protected areas</narrative>\n    <chart url="https://ourworldindata.org/grapher/terrestrial-protected-areas"/>\n  </item>\n  <item>\n    <narrative>Terrestrial Key Biodiversity Areas (KBAs)</narrative>\n    <chart url="https://ourworldindata.org/grapher/protected-terrestrial-biodiversity-sites"/>\n  </item>\n  <item>\n    <narrative>Freshwater Key Biodiversity Areas (KBAs)</narrative>\n    <chart url="https://ourworldindata.org/grapher/proportion-of-important-sites-for-freshwater-biodiversity-covered-by-protected-areas"/>\n  </item>\n</chart-story>',
      },
      {
        slug: "sdgs/quality-education",
        gdocType: "article",
        xhtml:
          '<chart-story>\n  <item>\n    <narrative>Primary education completion rate</narrative>\n    <chart url="https://ourworldindata.org/grapher/completion-rate-of-primary-education"/>\n  </item>\n  <item>\n    <narrative>Lower secondary education completion rate</narrative>\n    <chart url="https://ourworldindata.org/grapher/completion-rate-of-lower-secondary-education"/>\n  </item>\n  <item>\n    <narrative>Upper secondary education completion rate</narrative>\n    <chart url="https://ourworldindata.org/grapher/completion-rate-of-upper-secondary-education-sdg"/>\n  </item>\n</chart-story>',
      },
    ],
  },
  code: {
    count: 7,
    examples: [
      {
        slug: "new-feature-embed-archived-charts",
        gdocType: "article",
        xhtml:
          '<code>\n  <line>&lt;iframe src="https://archive.ourworldindata.org/20250626-192628/grapher/universal-suffrage-lexical.html?time=1925&amp;region=Europe&amp;globe=1&amp;globeRotation=55%2C10&amp;globeZoom=2.95" loading="lazy" style="width: 100%; height: 600px; border: 0px none;" allow="web-share; clipboard-write"&gt;&lt;/iframe&gt;</line>\n</code>',
      },
      {
        slug: "faqs",
        gdocType: "about-page",
        xhtml:
          '<code>\n  <line>&lt;iframe src="https://ourworldindata.org/grapher/child-mortality?time=1992..latest&amp;country=~OWID_AFR&amp;tab=chart" loading="lazy" style="width: 100%; height: 600px; border: 0px none;" allow="web-share; clipboard-write"&gt;&lt;/iframe&gt;</line>\n</code>',
      },
    ],
  },
  "conditional-section": {
    count: 1,
    examples: [
      {
        slug: "energy",
        gdocType: "profile",
        xhtml:
          '<conditional-section include="Low-income countries, Lower-middle-income countries">\n  <heading level="1">What share of $entityName’s population has access to electricity?</heading>\n  <text>Electricity is a good that adds massive value to modern life: from having light at night; to washing clothes; cooking meals; running machinery; or connecting with people across the world. Many would argue that it is a crucial for poverty alleviation, economic growth and improved living standards. \n    <ref url="#note-1">\n      <sup>1</sup>\n    </ref>\n  </text>\n  <text>This interactive chart shows the percentage of people that has access to electricity.</text>\n  <chart url="https://ourworldindata.org/grapher/share-of-the-population-with-access-to-electricity?tab=line&amp;country=$entityCode"/>\n  <prominent-link url="https://ourworldindata.org/grapher/people-without-electricity-country?country=$entityCode"/>\n  <heading level="1">What share of $entityName’s population has access to clean fuels for cooking?</heading>\n  <text>Having clean fuels and technologies for cooking — meaning non-solid fuels such as natural gas, ethanol or even electric technologies — makes these processes more efficient, saving both time and energy.</text>\n  <text>But it also comes with massive health benefits. The use of solid fuels for cooking — such as charcoal, crop waste, or dung — is a can lead to premature deaths and ill-health from \n    <a href="https://ourworldindata.org/indoor-air-pollution">indoor air pollution</a>.\n  </text>\n  <text>This interactive chart shows the percentage of the population that has access to clean cooking fuels for cooking.</text>\n  <chart url="https://ourworldindata.org/grapher/access-to-clean-fuels-and-technologies-for-cooking?tab=line&amp;country=$entityCode"/>\n  <prominent-link url="https://ourworldindata.org/grapher/number-without-clean-cooking-fuel?country=$entityCode"/>\n</conditional-section>',
      },
    ],
  },
  "cookie-notice": {
    count: 1,
    examples: [{ slug: "cookie-notice", gdocType: "about-page", xhtml: "<cookie-notice/>" }],
  },
  "country-profile-selector": {
    count: 4,
    examples: [
      {
        slug: "population-growth",
        gdocType: "topic-page",
        xhtml:
          '<country-profile-selector url="https://docs.google.com/document/d/1j2ighNKbYV0YtVxOX7iPxXjfO9-mWE791EQ107ogsp8/edit" description="Explore the key metrics on population and demography for a country of your choice. How is the population size changing? What about key metrics such as fertility rate, life expectancy, and migration? And how might the population structure change in the future?"/>',
      },
      {
        slug: "energy",
        gdocType: "topic-page",
        xhtml:
          '<country-profile-selector url="https://docs.google.com/document/u/0/d/1WddzFBTI8wF_KmJWRm7xQ3jydyiS3dIRI6o8KDS9NeE/edit" description="Explore the key metrics on energy for a country of your choice. How much energy is used overall? Which sources is it produced from? Is progress being made on decarbonizing the energy mix?"/>',
      },
    ],
  },
  cta: {
    count: 182,
    examples: [
      {
        slug: "top-of-the-charts-2025",
        gdocType: "article",
        xhtml:
          '<cta text="Explore the data and read more about how life expectancy is measured" url="https://ourworldindata.org/life-expectancy-how-is-it-calculated-and-how-should-it-be-interpreted"/>',
      },
      {
        slug: "hunger-levels-have-increased-across-africa-over-the-last-decade",
        gdocType: "data-insight",
        xhtml:
          '<cta text="Explore this data interactively, for all countries and regions in the world." url="https://ourworldindata.org/grapher/prevalence-of-undernourishment?tab=slope&amp;time=2014..latest&amp;country=Sub-Saharan+Africa+%28FAO%29~Africa+%28FAO%29~Eastern+Africa+%28FAO%29~Western+Africa+%28FAO%29~Southern+Africa+%28FAO%29~Northern+Africa+%28FAO%29~Middle+Africa+%28FAO%29"/>',
      },
    ],
  },
  "data-callout": {
    count: 38,
    examples: [
      {
        slug: "population-demography",
        gdocType: "profile",
        xhtml:
          '<data-callout url="https://ourworldindata.org/grapher/population-by-age-group-with-projections?country=$entityCode">\n  <heading level="2">How will $entityName’s age structure change in the future?</heading>\n  <text>As we covered earlier in this profile, the structure and age distribution of a population can be just as important as the total number of people.</text>\n  <text>The chart below shows how the population of different age groups is projected to change in $entityName through to the end of the century. Again, this is based on the UN’s medium population scenario.</text>\n  <chart url="https://ourworldindata.org/grapher/population-by-age-group-with-projections?country=$entityCode"/>\n</data-callout>',
      },
      {
        slug: "health",
        gdocType: "profile",
        xhtml:
          '<data-callout url="https://ourworldindata.org/grapher/life-expectancy-at-different-ages?country=$entityCode">\n  <heading level="2">What is $entityName’s life expectancy at different ages?</heading>\n  <text>Life expectancy at birth is often sensitive to death rates at younger ages. In particular, life expectancy is low when child mortality rates are high. These figures would tell you very little about how long a 40, 50, or 60-year-old could expect to live.</text>\n  <text>It’s therefore useful to look at life expectancy at different ages. This is shown in the chart for 10, 25, 45, 65, and 80-year-olds.</text>\n  <chart url="https://ourworldindata.org/grapher/life-expectancy-at-different-ages?country=$entityCode"/>\n</data-callout>',
      },
    ],
  },
  donors: { count: 1, examples: [{ slug: "funding", gdocType: "about-page", xhtml: "<donors/>" }] },
  "entry-summary": { count: 0, examples: [] },
  "expandable-paragraph": {
    count: 58,
    examples: [
      {
        slug: "technology-long-run",
        gdocType: "article",
        xhtml:
          '<expandable-paragraph>\n  <text>The recent speed of technological change makes it difficult to picture the history of technology in one visualization. When you visualize this development on a linear timeline, then most of the timeline is almost empty, while all the action is crammed into the right corner:</text>\n  <image filename="linear-timeline-long-run.png" hasOutline="false"/>\n  <text>In my large visualization here, I tried to avoid this problem and instead show the long history of technology in a way that lets you see when each technological breakthrough happened and how, within the last millennia, there was a continuous acceleration of technological change.</text>\n</expandable-paragraph>',
      },
      {
        slug: "wrong-about-the-world",
        gdocType: "article",
        xhtml:
          '<expandable-paragraph>\n  <text>For a \n    <a href="https://ourworldindata.org/max-un-slides">talk</a> on this I made this summary of the charts above and I post it here in case you find it helpful.\n  </text>\n  <image filename="4-Perception-summary.png" alt="" hasOutline="true"/>\n</expandable-paragraph>',
      },
    ],
  },
  expander: {
    count: 13,
    examples: [
      {
        slug: "wild-mammals-birds-biomass",
        gdocType: "article",
        xhtml:
          '<expander title="Humans" subtitle="How do researchers estimate the total biomass of humans?">\n  <text>To calculate the biomass of humans, the authors take global population figures for 2021 from the UN Population Division’s \n    <a href="https://population.un.org/wpp/downloads/">World Population Prospects</a> and multiply this by an age-weighted average body mass of 50 kilograms per person. This is relatively small for an adult, but when averaged across children and adults, it seems like a reasonable estimate.\n  </text>\n  <text>In 2021, the global population \n    <a href="https://ourworldindata.org/explorers/population-and-demography?time=earliest..2021&amp;country=~OWID_WRL&amp;indicator=Population&amp;Sex=Both+sexes&amp;Age=Total&amp;Projection+scenario=None">was around</a> 7.95 billion. Multiplying by 50 kilograms gives a total weight of 398 million tonnes.\n  </text>\n</expander>',
      },
      {
        slug: "trade-and-globalization",
        gdocType: "linear-topic-page",
        xhtml:
          '<expander title="What if we look at where countries export their goods?" heading="Additional information">\n  <text>You can find the equivalent map for exports \n    <a href="https://ourworldindata.org/grapher/countrys-top-destination-for-exports-of-goods?tab=map&amp;time=2023&amp;country=IRL~IDN~BEL~FSM">here</a>. China is also the largest export destination for many countries, but it is much less dominant than on the import side. While many countries around the world buy goods from China, China’s own imports are more concentrated: they focus on \n    <a href="https://oec.world/en/profile/country/chn?selector343id=Import&amp;selector359id=HS2">specific products</a> (like raw materials and commodities) and partners.\n  </text>\n</expander>',
      },
    ],
  },
  "explore-data-section": { count: 4, examples: [] },
  "explorer-tiles": {
    count: 1,
    examples: [
      {
        slug: "owid-homepage",
        gdocType: "homepage",
        xhtml:
          '<explorer-tiles title="Data explorers" subtitle="Interactive visualization tools to explore a wide range of related indicators.">\n  <explorer url="https://ourworldindata.org/explorers/poverty-explorer"/>\n  <explorer url="https://ourworldindata.org/explorers/population-and-demography"/>\n  <explorer url="https://ourworldindata.org/explorers/global-health"/>\n  <explorer url="https://ourworldindata.org/explorers/energy"/>\n</explorer-tiles>',
      },
    ],
  },
  "featured-data-insights": {
    count: 8,
    examples: [
      {
        slug: "government-spending",
        gdocType: "linear-topic-page",
        xhtml: "<featured-data-insights/>",
      },
      {
        slug: "happiness-and-life-satisfaction",
        gdocType: "linear-topic-page",
        xhtml: "<featured-data-insights/>",
      },
    ],
  },
  "featured-metrics": {
    count: 9,
    examples: [
      { slug: "government-spending", gdocType: "linear-topic-page", xhtml: "<featured-metrics/>" },
      {
        slug: "happiness-and-life-satisfaction",
        gdocType: "linear-topic-page",
        xhtml: "<featured-metrics/>",
      },
    ],
  },
  "gray-section": {
    count: 50,
    examples: [
      {
        slug: "democracy",
        gdocType: "topic-page",
        xhtml:
          '<gray-section>\n  <heading level="1">Explore Data on Democracy</heading>\n  <chart url="https://ourworldindata.org/explorers/democracy"/>\n  <text>This explorer seeks to make data on democracy easier to access and understand. It provides and explains data from seven leading democracy datasets: their main democracy measures, indicators of specific characteristics, and global and regional overviews. You can learn more about the approaches — \n    <b>and which democracy measure may be best to answer your questions</b> — in our article explaining how researchers measure democracy:\n  </text>\n  <prominent-link url="https://docs.google.com/document/d/1vMsru_zjboUD_W5aBXoMKMMxCxqyJ4oYVCfchYBzDQM/edit"/>\n</gray-section>',
      },
      {
        slug: "environmental-impacts-of-food",
        gdocType: "topic-page",
        xhtml:
          '<gray-section>\n  <heading level="1">Explore data on the Environmental Impacts of Food</heading>\n  <chart url="https://ourworldindata.org/explorers/food-footprints?facet=none&amp;Commodity+or+Specific+Food+Product=Commodity&amp;Environmental+Impact=Carbon+footprint&amp;Kilogram+%2F+Protein+%2F+Calories=Per+kilogram&amp;By+stage+of+supply+chain=false&amp;country=Bananas~Beef+%28beef+herd%29~Beef+%28dairy+herd%29~Cheese~Eggs~Lamb+%26+Mutton~Milk~Maize~Nuts~Pig+Meat~Peas~Potatoes~Poultry+Meat~Rice~Tomatoes~Wheat+%26+Rye~Tofu+%28soybeans%29~Prawns+%28farmed%29&amp;hideControls=false"/>\n</gray-section>',
      },
    ],
  },
  "guided-chart": {
    count: 15,
    examples: [
      {
        slug: "trade-and-globalization",
        gdocType: "linear-topic-page",
        xhtml:
          '<guided-chart>\n  <aside position="right">You can \n    <glink url="https://ourworldindata.org/grapher/growth-of-global-trade?yScale=log">switch this chart to a logarithmic scale.</glink> This will help you see that, over the long run, growth has roughly followed an exponential path.\n  </aside>\n  <text>What the chart shows is the long-run expansion of international trade: the average volume of imports and exports in 2024 was more than two thousand times larger than in 1800, after adjusting for inflation.\n    <ref url="#note-1">\n      <sup>1</sup>\n    </ref>\n  </text>\n  <chart url="https://ourworldindata.org/grapher/growth-of-global-trade"/>\n</guided-chart>',
      },
      {
        slug: "female-labor-supply",
        gdocType: "linear-topic-page",
        xhtml:
          '<guided-chart>\n  <chart url="https://ourworldindata.org/grapher/female-labor-force-participation-rate-by-age?tab=discrete-bar&amp;time=latest"/>\n</guided-chart>',
      },
    ],
  },
  heading: {
    count: 4888,
    examples: [
      {
        slug: "sdgs/industry-innovation-infrastructure",
        gdocType: "article",
        xhtml:
          '<heading level="3" supertitle="SDG Indicator 9.4.1">CO\n  <sub>2</sub> emissions per unit of value added\n</heading>',
      },
      {
        slug: "sdgs/sustainable-cities",
        gdocType: "article",
        xhtml:
          '<heading level="2" supertitle="Target 11.c                                                  ">Support least developed countries in sustainable and resilient building</heading>',
      },
    ],
  },
  "homepage-intro": {
    count: 1,
    examples: [
      {
        slug: "owid-homepage",
        gdocType: "homepage",
        xhtml:
          '<homepage-intro>\n  <featured-work url="https://docs.google.com/document/d/1_1Lulu1muRprdpbPB1nN1UPDQfPOEUFR3aCbfOvagJM/edit?tab=t.0" kicker="Topic page" isNew="true"/>\n  <featured-work url="https://docs.google.com/document/d/12hNREWcrwyOrJugzc7gYHN5Qv_UJBJ-GnY_FzMbXByE/edit?tab=t.0" kicker="From our classics"/>\n  <featured-work url="https://docs.google.com/document/d/19IAblawAm0qGaPHS64hp4cMB8R2A8pZp04Fple1P7g0/edit?tab=t.cqu1zqrixzbm" kicker="Article · 8 min read"/>\n  <featured-work url="https://docs.google.com/document/d/1C4MSxcjodtCNqwZ7qHG4dCWcAdGlOFIWdajT7LuCiJg/edit" kicker="Announcement"/>\n</homepage-intro>',
      },
    ],
  },
  "homepage-search": {
    count: 1,
    examples: [{ slug: "owid-homepage", gdocType: "homepage", xhtml: "<homepage-search/>" }],
  },
  "horizontal-rule": {
    count: 313,
    examples: [
      { slug: "education-in-ethiopia-yl", gdocType: "article", xhtml: "<horizontal-rule/>" },
      { slug: "how-and-why-econ-complexity", gdocType: "article", xhtml: "<horizontal-rule/>" },
    ],
  },
  html: {
    count: 73,
    examples: [
      {
        slug: "conflict-data-how-do-researchers-measure-armed-conflicts-and-their-deaths",
        gdocType: "article",
        xhtml:
          '<html value="&lt;table class=&quot;html-table&quot;&gt;&lt;tr&gt;&lt;td&gt;UCDP&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Total, combatant, and civilian deaths, due to fighting&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Project Mars&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Deaths of combatants, due to fighting&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Militarized Interstate Events&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Deaths of combatants, due to fighting&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Correlates of War — War Data&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Deaths of combatants, due to fighting, disease, and starvation&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Correlates of War — Militarized Interstate Disputes&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Deaths of combatants, due to fighting&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Peace Research Institute Oslo&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Deaths of combatants and civilians, due to fighting&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Conflict Catalog&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Total, combatant, and civilian deaths, due to fighting, disease, and starvation&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"/>',
      },
      {
        slug: "democracies-measurement",
        gdocType: "article",
        xhtml:
          '<html value="&lt;table class=&quot;html-table&quot;&gt;&lt;tr&gt;&lt;td&gt;Varieties of Democracy&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Narrow and broader: electoral, liberal, participatory, deliberative, or egalitarian democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Regimes of the World&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Narrow: electoral or liberal democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Lexical Index&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Narrow: electoral (or liberal) democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Freedom House&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Narrow: electoral or liberal democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Bertelsmann Transformation Index&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Broad: electoral, liberal, participatory, deliberative, and effective democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Economist Intelligence Unit&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Broad: electoral, liberal, participatory, deliberative, and effective democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Polity&lt;/td&gt;&lt;td&gt;&lt;ul&gt;&lt;li&gt;Narrow: electoral and liberal democracy&lt;/li&gt;&lt;/ul&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"/>',
      },
    ],
  },
  image: {
    count: 1290,
    examples: [
      {
        slug: "global-fight-polio",
        gdocType: "article",
        xhtml:
          '<image filename="Polio-cases-over-time-by-world-region.jpg" alt="A big chart that shows that the annual number of people paralyzed by polio was reduced by over 99% in the last four decades." hasOutline="false">\n  <caption>Paralytic polio cases since 1980, by world region\n    <ref url="#note-4">\n      <sup>4</sup>\n    </ref>\n  </caption>\n</image>',
      },
      {
        slug: "a-history-of-global-living-conditions",
        gdocType: "article",
        xhtml:
          '<image filename="World-as-100-people-2024.png" alt="A summary visualization that shows how the world has changed over the last two centuries — poverty is down, education up, child mortality down, democracy" hasOutline="true">\n  <caption>The world as 100 people over the last two centuries</caption>\n</image>',
      },
    ],
  },
  "key-indicator": {
    count: 8,
    examples: [
      {
        slug: "owid-homepage",
        gdocType: "homepage",
        xhtml:
          '<key-indicator datapageUrl="https://ourworldindata.org/grapher/cross-country-literacy-rates" title="When has literacy become a widespread skill?" source="Long-run estimates collated from multiple sources by Our World in Data">\n  <text>Literacy is a foundational skill. Children need to learn to read so that they can read to learn. When we fail to teach this foundational skill, people have fewer opportunities to lead the rich and interesting lives that a good education offers.</text>\n  <text>The historical data shows that only a very small share of the population, a tiny elite, was able to read and write. Over the course of the last few generations, literacy levels increased, but \n    <a href="https://ourworldindata.org/better-learning">it remains</a> an important challenge for our time to provide this foundational skill to all.\n  </text>\n  <text>At Our World in Data, \n    <a href="https://ourworldindata.org/how-is-literacy-measured">we investigated</a> the strengths and shortcomings of the available data on literacy. Based on this work, our team brought together the long-run data shown in the chart by combining several different sources, including historical and recent UNESCO data and a range of research publications.\n  </text>\n</key-indicator>',
      },
      {
        slug: "owid-homepage",
        gdocType: "homepage",
        xhtml:
          '<key-indicator datapageUrl="https://ourworldindata.org/grapher/life-expectancy" title="How has people’s life expectancy changed over time?" source="Long-run estimates collated from multiple sources by Our World in Data">\n  <text>Across the world, people are living longer. In 1900, the global average life expectancy of a newborn was 32 years. By 2021, this had more than doubled to 71 years.</text>\n  <text>Big improvements were achieved by countries \n    <a href="https://ourworldindata.org/life-expectancy-globally">around the world</a>. The chart shows that life expectancy has more than doubled in every region of the world. This improvement is not only due to declining child mortality; life expectancy increased \n    <a href="https://ourworldindata.org/its-not-just-about-child-mortality-life-expectancy-improved-at-all-ages">at all ages</a>.\n  </text>\n  <text>This visualization shows long-run estimates of life expectancy brought together by our team from several different data sources. It also shows that the \n    <a href="https://ourworldindata.org/coronavirus">COVID-19 pandemic</a> led to reduced life expectancy worldwide.\n  </text>\n</key-indicator>',
      },
    ],
  },
  "key-indicator-collection": { count: 1, examples: [] },
  "key-insights": { count: 24, examples: [] },
  "latest-data-insights": {
    count: 1,
    examples: [{ slug: "owid-homepage", gdocType: "homepage", xhtml: "<latest-data-insights/>" }],
  },
  list: {
    count: 694,
    examples: [
      {
        slug: "ethnographic-and-archaeological-evidence-on-violent-deaths",
        gdocType: "article",
        xhtml:
          "<list>\n  <li>\n    <i>My source for the data:</i> Walker and Bailey (2013)\n  </li>\n  <li>\n    <i>Source that my source quoted:</i> Werner, D. W. (1980). The making of a Mekranoti chief: The psychological and social determinants of leadership in a native South American Society. PhD dissertation. City University of New York, New York.\n  </li>\n  <li>\n    <i>Comment:</i> 75% of victims were male, Total numbers: 83 killings in 237 deaths\n  </li>\n</list>",
      },
      {
        slug: "excess-mortality-covid",
        gdocType: "article",
        xhtml:
          '<list>\n  <li>\n    <a href="https://www.who.int/publications/m/item/methods-for-estimating-the-excess-mortality-associatedwith-the-covid-19-pandemic">Methods for estimating the excess mortality associated with the COVID-19 pandemic</a>\n  </li>\n  <li>Knutson et al. (2023). \n    <a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C5&amp;q=DOI%3A+10.1214%2F22-AOAS1673&amp;btnG=">Estimating global and country-specific excess mortality during the Covid-19 pandemic</a>. \n    <i>The Annals of Applied Statistics.</i>\n  </li>\n</list>',
      },
    ],
  },
  "ltp-toc": {
    count: 8,
    examples: [
      {
        slug: "natural-disasters",
        gdocType: "linear-topic-page",
        xhtml: '<ltp-toc title="Contents"/>',
      },
      {
        slug: "global-education",
        gdocType: "linear-topic-page",
        xhtml: '<ltp-toc title="Contents"/>',
      },
    ],
  },
  "missing-data": {
    count: 9,
    examples: [
      { slug: "sdgs/sustainable-cities", gdocType: "article", xhtml: "<missing-data/>" },
      { slug: "sdgs/life-on-land", gdocType: "article", xhtml: "<missing-data/>" },
    ],
  },
  "narrative-chart": {
    count: 54,
    examples: [
      {
        slug: "britain-safest-roads-history",
        gdocType: "article",
        xhtml:
          '<narrative-chart name="drink-drive-collisions-have-fallen-more-quickly-than-all-road-collisions-in-great-britain-over-the-past-50-years"/>',
      },
      {
        slug: "measles-vaccines-save-lives",
        gdocType: "article",
        xhtml:
          '<narrative-chart name="number-of-lives-saved-by-measles-and-childhood-vaccinations-from-1974-to-2024"/>',
      },
    ],
  },
  "numbered-list": {
    count: 32,
    examples: [
      {
        slug: "extinction-risk-definition",
        gdocType: "article",
        xhtml:
          "<numbered-list>\n  <li>If the population size is very small.</li>\n  <li>If the population size is small \n    <i>and</i> it’s declining.\n  </li>\n  <li>If there has been a large \n    <i>decline</i> in population size (regardless of its total size).\n  </li>\n  <li>The geographic range of the species – the area or region it lives in – is small and declining.</li>\n</numbered-list>",
      },
      {
        slug: "optimism-and-pessimism",
        gdocType: "article",
        xhtml:
          "<numbered-list>\n  <li>Individuals rarely think about grand issues such as the state of the nation or world, and so respond with an 'on-the-spot' answer that may not be well considered or even a true reflection of their beliefs.</li>\n  <li>The framing can influence the individual's response. Moreover, the question itself may bias responses; 'who would bother to ask if everything were okay?'</li>\n  <li>Responses to questions such as these (and more general questions about happiness or life satisfaction) are heavily influenced by ephemeral recent events. In psychology this is referred to as the 'availability bias'.</li>\n</numbered-list>",
      },
    ],
  },
  people: {
    count: 3,
    examples: [
      {
        slug: "new-trustees-claire-melamed-michael-blastland",
        gdocType: "article",
        xhtml:
          '<people>\n  <person name="Dr. Claire Melamed" image="claire_melamed_photo.png" url="">\n    <text>Claire Melamed leads the Global Partnership for Sustainable Development Data’s Secretariat.</text>\n    <text>She was previously Managing Director of the Overseas Development Institute, has worked in the office of the UN Secretary General, and for a number of NGOs.</text>\n    <text>She is an Affiliated Researcher at the Bennett Institute for Public Policy at the University of Cambridge and serves on the Board of Full Fact. She is based in London.</text>\n  </person>\n  <person name="Michael Blastland" image="michael_blastland_photo.jpg" url="">\n    <text>Michael Blastland is a writer and broadcaster, best known as the creator (with Andrew Dilnot) of More or Less on Radio 4, and as presenter and producer of numerous other series.</text>\n    <text>In a varied career, he’s also written several popular science books about numbers, chance, risk, and related subjects; was a board member of the Winton Centre for Risk and Evidence Communication; has advised large-scale research projects; taught for many years on BBC courses for senior journalists and elsewhere; and most recently served as a non-executive director and deputy chair of Royal Papworth Hospital, and co-authored a BBC inquiry into the impartiality of its coverage of tax, public spending, borrowing, and debt.</text>\n  </person>\n</people>',
      },
      {
        slug: "organization",
        gdocType: "about-page",
        xhtml:
          '<people>\n  <person name="Professor Sir David Hendry" url="">\n    <text>David Hendry was a founding member of our Board of Trustees. He is co-director of \n      <a href="https://www.nuffield.ox.ac.uk/our-research/research-centres/climate-econometrics/">Climate Econometrics</a> at Nuffield College and was previously a Professor of Economics at Oxford University, where he was the Chairman of the Economics Department from 2001 to 2007. He was knighted in 2009, and he is an Honorary Vice-President and past President of the Royal Economic Society.\n    </text>\n  </person>\n  <person name="Professor Stefano Caria" url="">\n    <text>Stefano Caria was a founding member of our Board of Trustees. He is a Professor in the Department of Economics at the \n      <a href="https://warwick.ac.uk/fac/soc/economics/">University of Warwick</a>, specializing in development economics. He is also affiliated with \n      <a href="https://www.povertyactionlab.org/">J-PAL,</a> \n      <a href="https://cepr.org/">CEPR,</a> \n      <a href="https://warwick.ac.uk/fac/soc/economics/research/centres/cage/">CAGE</a>, and the EEE program at STICERD.\n    </text>\n  </person>\n</people>',
      },
    ],
  },
  "people-rows": {
    count: 7,
    examples: [
      {
        slug: "team",
        gdocType: "about-page",
        xhtml:
          '<people-rows columns="2">\n  <person name="Dr. Charlie Giattino" image="charliegiattino.jpg" title="Communications &amp; Outreach Strategy Lead" url="https://docs.google.com/document/d/1Zpw0EpBU12W8OTIPvXVKiErbdSvc4zfaN63_lXmpi_Q/edit">\n    <text>Charlie joined us in 2020. He has worked across our team: initially joining as a researcher, later moving to our operations team, and now leading our communications. He completed his Ph.D. in cognitive neuroscience at Duke University.</text>\n    <socials>\n      <social url="mailto:charlie@ourworldindata.org" text="charlie@ourworldindata.org" type="email"/>\n      <social url="https://x.com/charliegiattino" text="@charliegiattino" type="x"/>\n    </socials>\n  </person>\n</people-rows>',
      },
      {
        slug: "team",
        gdocType: "about-page",
        xhtml:
          '<people-rows columns="2">\n  <person name="Antoinette Finnegan" image="antoinette_team_page.jpeg" title="HR Manager" url="">\n    <text>Antoinette joined us in 2023 as our Human Resources (HR) Manager. She most recently worked in HR for a biotech spinout, and also has experience in fundraising and marketing.</text>\n    <socials>\n      <social url="mailto:antoinette@ourworldindata.org" text="antoinette@ourworldindata.org" type="email"/>\n    </socials>\n  </person>\n  <person name="Natalie Reynolds-Garcia" image="Natalie.png" title="Operations and Administration Officer" url="">\n    <text>Natalie joined us in 2022 as Operations and Administration Officer. Her background is in research administration and education, having taught Spanish, French and English. She was previously the administrator for the Rees Centre at the University at Oxford.</text>\n    <socials>\n      <social url="mailto:natalie@ourworldindata.org" text="natalie@ourworldindata.org" type="email"/>\n    </socials>\n  </person>\n  <person name="Valerie Rogers Muigai, CGMA" image="Valerie-headshot-e1656491769502.jpg" title="Senior Finance and Operations Manager" url="">\n    <text>Valerie joined OWID in 2021. She is a CGMA-certified management accountant with an MBA from Oxford Saïd Business School. Before joining OWID, she spent over a decade working in social enterprise and international development in East Africa.</text>\n    <socials>\n      <social url="mailto:valerie@ourworldindata.org" text="valerie@ourworldindata.org" type="email"/>\n    </socials>\n  </person>\n</people-rows>',
      },
    ],
  },
  person: {
    count: 71,
    examples: [
      {
        slug: "new-trustees-claire-melamed-michael-blastland",
        gdocType: "article",
        xhtml:
          '<person name="Michael Blastland" image="michael_blastland_photo.jpg" url="">\n  <text>Michael Blastland is a writer and broadcaster, best known as the creator (with Andrew Dilnot) of More or Less on Radio 4, and as presenter and producer of numerous other series.</text>\n  <text>In a varied career, he’s also written several popular science books about numbers, chance, risk, and related subjects; was a board member of the Winton Centre for Risk and Evidence Communication; has advised large-scale research projects; taught for many years on BBC courses for senior journalists and elsewhere; and most recently served as a non-executive director and deputy chair of Royal Papworth Hospital, and co-authored a BBC inquiry into the impartiality of its coverage of tax, public spending, borrowing, and debt.</text>\n</person>',
      },
      {
        slug: "team",
        gdocType: "about-page",
        xhtml:
          '<person name="Tuna Acisu" image="Tuna-0004.jpg" title="Data Scientist" url="https://docs.google.com/document/d/1yGeA21znMpCd70qZTVM34tlpZOrC6vKIGndL4B-sd7U/edit">\n  <text>Tuna joined us in 2024. She previously worked on machine learning for epigenetic data and in management consulting. She has an M.Sc. in Data Science from the Technical University of Munich.</text>\n  <socials>\n    <social url="mailto:tuna@ourworldindata.org" text="tuna@ourworldindata.org" type="email"/>\n    <social url="https://x.com/antea04" text="@antea04" type="x"/>\n    <social url="https://bsky.app/profile/antea04.bsky.social" text="@antea04.bsky.social" type="bluesky"/>\n    <social url="https://www.linkedin.com/in/tuna-acisu-a00328140" text="Tuna Acisu" type="linkedin"/>\n  </socials>\n</person>',
      },
    ],
  },
  "pill-row": {
    count: 8,
    examples: [
      {
        slug: "bertha-rohenkohl",
        gdocType: "author",
        xhtml:
          '<pill-row title="Topics covered by Bertha on Our World in Data">\n  <pill url="https://docs.google.com/document/d/1UjJLoGF5VMfn8U4C3ZSJQrPhc_jFRkeEhrhz5Ksfq7M/edit" text="Poverty"/>\n  <pill url="https://docs.google.com/document/d/10M5sJhpAaXXC7O9flEywoaeT3m10pDe1_sErOOe-PeI/edit" text="Work and Employment"/>\n  <pill url="https://docs.google.com/document/d/1scFKpuRQ13hmruDYgL3f-nMKNVbjW8YtM-u6mxqLa9k/edit?tab=t.0" text="Trade and Globalization"/>\n  <pill url="https://docs.google.com/document/d/1yzOrFd6uWvrAl2oFB3S67oOSbhgL1ffPHxjAqS7i-4w/edit" text="Economic Inequality"/>\n  <pill url="https://docs.google.com/document/d/1gVSV2gqzPSTMI80gmHEgbaKeWalj6daqe519RtZaJ7I/edit" text="Economic Growth"/>\n  <pill url="https://docs.google.com/document/d/1Hz0E15ltNEcTdf_M6tqSmHyhWrN_11DujuCA-WttU6w/edit?tab=t.0" text="Government Spending"/>\n</pill-row>',
      },
      {
        slug: "owid-homepage",
        gdocType: "homepage",
        xhtml:
          '<pill-row title="Popular pages">\n  <pill url="https://ourworldindata.org/poverty" text="Poverty"/>\n  <pill url="https://ourworldindata.org/child-mortality" text="Child Mortality"/>\n  <pill url="https://ourworldindata.org/global-education" text="Global Education"/>\n  <pill url="https://ourworldindata.org/co2-and-greenhouse-gas-emissions" text="CO₂ Emissions"/>\n  <pill url="https://ourworldindata.org/migration" text="Migration"/>\n  <pill url="https://ourworldindata.org/war-and-peace" text="War &amp; Peace"/>\n  <pill url="https://ourworldindata.org/life-expectancy" text="Life Expectancy"/>\n  <pill url="https://ourworldindata.org/population-growth" text="Population Growth"/>\n  <pill url="https://ourworldindata.org/artificial-intelligence" text="Artificial Intelligence"/>\n</pill-row>',
      },
    ],
  },
  "prominent-link": {
    count: 672,
    examples: [
      {
        slug: "poverty-growth-needed",
        gdocType: "article",
        xhtml:
          '<prominent-link url="https://ourworldindata.org/poverty-minimum-growth-needed" title="How much economic growth is necessary to reduce global poverty substantially?" description="In a follow up post I made the statements above more concrete and looked at the depth of global poverty today to get a quantitative sense of just how much the global income distribution would need to change to reduce global poverty substantially" thumbnail="poverty-minimum-growth-needed-featured-image.png"/>',
      },
      {
        slug: "causes-of-death",
        gdocType: "topic-page",
        xhtml:
          '<prominent-link url="https://ourworldindata.org/how-are-causes-of-death-registered-around-the-world" title="How are causes of death registered around the world?" description="When people die, the cause of their death is usually officially registered in their country’s national system. How is the cause determined?" thumbnail="Cause-of-death-registration-thumbnail.png"/>',
      },
    ],
  },
  "pull-quote": {
    count: 44,
    examples: [
      {
        slug: "most-people-care-about-farm-animals-our-food-system-doesnt-reflect-that",
        gdocType: "article",
        xhtml:
          '<pull-quote align="right-center" quote="There is a clear gap between what people want — meat produced without suffering — and what the food system delivers.">\n  <text>If we want to close the gap between our food system and our values, we can’t just rely on changing people’s diets. Several other levers need to move together, including innovation and policy.</text>\n  <text>Food companies offer products that look and taste similar to meat and fish, but are made from plants. And soon, we will be able to buy cultivated meat, produced without raising and slaughtering animals.\n    <ref url="#note-4">\n      <sup>4</sup>\n    </ref>\n  </text>\n</pull-quote>',
      },
      {
        slug: "pesticide-bans-suicide-prevention",
        gdocType: "article",
        xhtml:
          '<pull-quote align="left-center" quote="A ban on highly hazardous pesticides in just 14 countries could save 28,000 lives each year and would cost only $30 million">\n  <text>But the research is convincing that banning selective HHPs has played a role in reducing the fatality of suicide attempts, saving thousands of lives each year in the process.</text>\n  <text>Some studies — although very few have modeled this — also suggest that it’s a relatively cost-effective intervention. This means it could save many lives, even in resource-constrained countries that don’t have large budgets to spend (which often means that mental health and suicide do not get attention at all).</text>\n</pull-quote>',
      },
    ],
  },
  recirc: {
    count: 59,
    examples: [
      {
        slug: "the-end-of-tuberculosis-that-wasnt",
        gdocType: "article",
        xhtml:
          '<recirc title="This is the second article in our three-part series on tuberculosis:">\n  <link url="https://docs.google.com/document/d/1BJvUh9_T06sVf2-ApMdTnxOh-LkdqTgGUyUToAXqL8Y/edit"/>\n  <link url="https://docs.google.com/document/d/114kkq1P3_AKM8D9RbiMDVbb50LE49GLW8rTrF4pfulI/edit"/>\n  <link url="https://docs.google.com/document/d/1IgvD1frfDsX_lAz3TV0RtbNOtBDk1avgGKMPTlbnlxQ/edit?tab=t.cqu1zqrixzbm"/>\n</recirc>',
      },
      {
        slug: "tuberculosis-history-decline",
        gdocType: "article",
        xhtml:
          '<recirc title="This is the first article in our three-part series on tuberculosis:">\n  <link url="https://docs.google.com/document/d/1BJvUh9_T06sVf2-ApMdTnxOh-LkdqTgGUyUToAXqL8Y/edit"/>\n  <link url="https://docs.google.com/document/d/114kkq1P3_AKM8D9RbiMDVbb50LE49GLW8rTrF4pfulI/edit"/>\n  <link url="https://docs.google.com/document/d/1IgvD1frfDsX_lAz3TV0RtbNOtBDk1avgGKMPTlbnlxQ/edit?tab=t.cqu1zqrixzbm"/>\n</recirc>',
      },
    ],
  },
  "research-and-writing": {
    count: 75,
    examples: [
      {
        slug: "medicine-biotech",
        gdocType: "topic-page",
        xhtml:
          '<research-and-writing heading="Research &amp; Writing">\n  <primary>\n    <link url="https://docs.google.com/document/d/1qiCu4Yl-YxNgj8cV_0MGB9p6z6WoLF3gFGFspsjK1qU/edit"/>\n  </primary>\n  <secondary>\n    <link url="https://docs.google.com/document/d/1e0HDWjfdRTrbLlAdUMPGtkqmLJJFw9ookSmgBU6JMPI/edit"/>\n    <link url="https://docs.google.com/document/d/1-YJoOYf5-_gfSFkJ6sNbMPkAI75VnOOGLSt18_4euL0/edit"/>\n  </secondary>\n  <row heading="More Articles on Medicine and Biotechnology">\n    <link url="https://docs.google.com/document/d/1-6S3Nsjrb7wFbNizDTvohHGcOzvDvva0UyDoKQUyXnQ/edit"/>\n    <link url="https://docs.google.com/document/d/19ytyrpTe5fYQCwAyz25egACwwr9kjyHJkYySzWlYg2Q/edit"/>\n    <link url="https://docs.google.com/document/d/1P8pu_FGx6fnJWw-xQBREe49uqN62rZAuARRrR2cdOjc/edit"/>\n    <link url="https://docs.google.com/document/d/1VrCiTsQYC6IoUqFoWl7E6QVHVrpgTcenjRjC5Xd9VVs/edit"/>\n  </row>\n</research-and-writing>',
      },
      {
        slug: "light-at-night",
        gdocType: "topic-page",
        xhtml:
          '<research-and-writing heading="Research &amp; Writing">\n  <primary>\n    <link url="https://ourworldindata.org/worlds-energy-problem" title="The world\'s energy problem" subtitle="The world faces two energy problems: most of our energy production still produces greenhouse gas emissions, and hundreds of millions lack access to energy entirely." authors="Max Roser" filename="Screen-Shot-2020-11-26-at-10.33.19.png"/>\n  </primary>\n  <secondary>\n    <link url="https://ourworldindata.org/whaling" title="Global whaling peaked in the 1960s" subtitle="Intense whaling for light and oil drove many of the world’s whale species close to extinction. But a dramatic decline in whale hunting since then has given them hopes of recovery." authors="Hannah Ritchie" filename="Whaling-featured-image.png"/>\n  </secondary>\n</research-and-writing>',
      },
    ],
  },
  "resource-panel": {
    count: 1,
    examples: [
      {
        slug: "corruption",
        gdocType: "linear-topic-page",
        xhtml:
          '<resource-panel icon="chart" kicker="Resources" title="Data on corruption" buttonText="See all data on this topic">\n  <link url="https://ourworldindata.org/grapher/bribery-prevalence-un" subtitle="United Nations Office on Drugs and Crime"/>\n  <link url="https://ourworldindata.org/grapher/bribery-incidence-for-firms" subtitle="World Bank Enterprise Surveys"/>\n  <link url="https://ourworldindata.org/grapher/political-corruption-index" subtitle="Varieties of Democracy Project"/>\n</resource-panel>',
      },
    ],
  },
  script: { count: 0, examples: [] },
  "sdg-grid": {
    count: 1,
    examples: [
      {
        slug: "sdgs",
        gdocType: "article",
        xhtml:
          '<sdg-grid>\n  <item goal="No Poverty" link="/sdgs/no-poverty"/>\n  <item goal="Zero Hunger" link="/sdgs/zero-hunger"/>\n  <item goal="Good Health and Well-Being" link="/sdgs/good-health-wellbeing"/>\n  <item goal="Quality Education" link="/sdgs/quality-education"/>\n  <item goal="Gender Equality" link="/sdgs/gender-equality"/>\n  <item goal="Clean Water and Sanitation" link="/sdgs/clean-water-sanitation"/>\n  <item goal="Affordable and Clean Energy" link="/sdgs/affordable-clean-energy"/>\n  <item goal="Decent Work and Economic Growth" link="/sdgs/economic-growth"/>\n  <item goal="Industry, Innovation and Infrastructure" link="/sdgs/industry-innovation-infrastructure"/>\n  <item goal="Reduced Inequalities" link="/sdgs/reduced-inequalities"/>\n  <item goal="Sustainable Cities and Communities" link="/sdgs/sustainable-cities"/>\n  <item goal="Responsible Consumption and Production" link="/sdgs/responsible-consumption-production"/>\n  <item goal="Climate Action" link="/sdgs/climate-action"/>\n  <item goal="Life Below Water" link="/sdgs/life-below-water"/>\n  <item goal="Life on Land" link="/sdgs/life-on-land"/>\n  <item goal="Peace, Justice and Strong Institutions" link="/sdgs/peace-justice-institutions"/>\n  <item goal="Partnerships for the Goals" link="/sdgs/global-partnerships"/>\n</sdg-grid>',
      },
    ],
  },
  "sdg-toc": {
    count: 17,
    examples: [
      { slug: "sdgs/peace-justice-institutions", gdocType: "article", xhtml: "<sdg-toc/>" },
      { slug: "sdgs/sustainable-cities", gdocType: "article", xhtml: "<sdg-toc/>" },
    ],
  },
  "side-by-side": {
    count: 201,
    examples: [
      {
        slug: "estimating-total-global-paralytic-polio-cases",
        gdocType: "article",
        xhtml:
          '<side-by-side>\n  <left>\n    <heading level="2">Results: comparison of reported cases vs. estimated cases</heading>\n    <text>In this chart you can compare the estimated number of polio cases with the number of reported cases.</text>\n    <text>It is important to note that these are rough estimates of the number of paralytic polio cases based on metrics of testing quality (non-polio AFP rate and AFP cases with adequate stool collection). Data on testing quality by country is not available before 2000.</text>\n  </left>\n  <right>\n    <chart url="https://ourworldindata.org/grapher/the-difference-between-the-reported-and-the-estimated-actual-number-of-paralytic-polio-cases"/>\n  </right>\n</side-by-side>',
      },
      {
        slug: "britain-safest-roads-history",
        gdocType: "article",
        xhtml:
          '<side-by-side>\n  <left>\n    <image filename="1926-car-uk.jpg" size="narrow" hasOutline="true">\n      <caption>Source: \n        <a href="https://commons.wikimedia.org/wiki/File:1926_Star_two-seater_Star_motor_car.jpg">Wolverhampton City Archives via Wikimedia Commons</a>\n      </caption>\n    </image>\n  </left>\n  <right>\n    <image filename="bournemouth-uk-1920s-car.jpg" size="narrow" hasOutline="true">\n      <caption>Source: \n        <a href="https://itoldya420.getarchive.net/media/bournemouth-springbourne-car-people-including-soldiers-outside-library-rp-b17e81">Mark Crombie, Flickr vintage topographical postcards collection</a>\n      </caption>\n    </image>\n  </right>\n</side-by-side>',
      },
    ],
  },
  "simple-text": { count: 7, examples: [] },
  socials: {
    count: 16,
    examples: [
      {
        slug: "max-roser",
        gdocType: "author",
        xhtml:
          '<socials>\n  <link url="https://x.com/MaxCRoser" text="@MaxCRoser" type="x"/>\n  <link url="https://bsky.app/profile/maxroser.bsky.social" text="@maxroser.bsky.social" type="bluesky"/>\n  <link url="https://www.instagram.com/max.roser.owid/" text="max.roser.owid" type="instagram"/>\n  <link url="https://www.threads.net/@max.roser.owid" text="@max.roser.owid" type="threads"/>\n  <link url="https://www.linkedin.com/in/max-roser-ox/" text="Max Roser" type="linkedin"/>\n  <link url="https://mas.to/@maxroser" text="@maxroser" type="mastodon"/>\n</socials>',
      },
      {
        slug: "bastian-herre",
        gdocType: "author",
        xhtml:
          '<socials>\n  <link url="mailto:bastian@ourworldindata.org" text="bastian@ourworldindata.org" type="email"/>\n  <link url="https://bsky.app/profile/bastianherre.bsky.social" text="@bastianherre.bsky.social" type="bluesky"/>\n  <link url="https://www.linkedin.com/in/bastian-herre-44ba64235/" text="Bastian Herre" type="linkedin"/>\n  <link url="https://www.bastianherre.com/" text="bastianherre.com" type="link"/>\n</socials>',
      },
    ],
  },
  "static-viz": {
    count: 8,
    examples: [
      {
        slug: "measles-vaccines-save-lives",
        gdocType: "article",
        xhtml:
          '<static-viz name="us-measles-heatmap" hasOutline="true">\n  <caption>This chart was inspired by Tynan DeBold and Dov Friedman’s \n    <a href="https://graphics.wsj.com/infectious-diseases-and-vaccines/">data visualizations</a> in the Wall Street Journal. Explore the data in \n    <a href="https://ourworldindata.org/grapher/reported-measles-case-rate-by-state-in-the-united-states">an interactive chart</a>. Scripts to recreate this chart can be found \n    <a href="https://github.com/owid/notebooks/tree/main/FionaSpooner/measles_heatmap">on GitHub</a>.\n  </caption>\n</static-viz>',
      },
      {
        slug: "vaccination",
        gdocType: "linear-topic-page",
        xhtml:
          '<static-viz name="us-measles-heatmap" hasOutline="true">\n  <caption>This chart was inspired by Tynan DeBold and Dov Friedman’s \n    <a href="https://graphics.wsj.com/infectious-diseases-and-vaccines/">data visualizations</a> in the Wall Street Journal. Explore the data in \n    <a href="https://ourworldindata.org/grapher/reported-measles-case-rate-by-state-in-the-united-states">an interactive chart</a>. Scripts to recreate this chart can be found \n    <a href="https://github.com/owid/notebooks/tree/main/FionaSpooner/measles_heatmap">on GitHub</a>.\n  </caption>\n</static-viz>',
      },
    ],
  },
  "sticky-left": {
    count: 13,
    examples: [
      {
        slug: "covid-cases",
        gdocType: "article",
        xhtml:
          '<sticky-left>\n  <left>\n    <chart url="https://ourworldindata.org/explorers/covid?facet=none&amp;hideControls=true&amp;Interval=7-day+rolling+average&amp;Relative+to+Population=true&amp;Color+by+test+positivity=false&amp;Metric=Confirmed+cases"/>\n  </left>\n  <right>\n    <text>There are often large differences in the population size between countries. Therefore, to compare cases between countries, it is more insightful to look at the number of confirmed cases \n      <i>as a rate</i> per million people.\n    </text>\n    <text>But some countries conduct very little testing, so their actual number of infections can be much higher than the number of confirmed cases shown here.</text>\n  </right>\n</sticky-left>',
      },
      {
        slug: "newsletters",
        gdocType: "article",
        xhtml:
          '<sticky-left>\n  <left>\n    <heading level="1">Data Insights</heading>\n    <text>\n      <b>Frequency: </b>Every few days.\n    </text>\n    <text>\n      <b>What is it? </b>Bite-sized insights on the world and how it’s changing.\n    </text>\n    <text>\n      <a href="https://us8.campaign-archive.com/?u=18058af086319ba6afad752ec&amp;id=2451f71f01">See an example of the Data Insights newsletter.</a>\n    </text>\n  </left>\n  <right>\n    <image filename="data-insights-newsletter.png" alt="A preview of our Data Insights newsletter." size="narrow" hasOutline="true">\n      <caption>A preview of our Data Insights newsletter.</caption>\n    </image>\n  </right>\n</sticky-left>',
      },
    ],
  },
  "sticky-right": {
    count: 406,
    examples: [
      {
        slug: "how-are-mental-illnesses-defined",
        gdocType: "article",
        xhtml:
          '<sticky-right>\n  <left>\n    <text>In the chart, you can see the estimated prevalence of people who meet the criteria to be diagnosed with each category of mental illness, as they are classified by the ICD manual.</text>\n    <text>As you can see, anxiety disorders and depressive disorders are more common. It’s estimated that around 3–4% of people worldwide have had them in the past year.</text>\n    <text>Bipolar disorder, schizophrenia and eating disorders are less common. For example, it’s estimated that 0.3% of people have schizophrenia worldwide.</text>\n  </left>\n  <right>\n    <chart url="https://ourworldindata.org/grapher/share-of-population-with-mental-illnesses"/>\n  </right>\n</sticky-right>',
      },
      {
        slug: "how-do-researchers-study-the-prevalence-of-mental-illnesses",
        gdocType: "article",
        xhtml:
          '<sticky-right>\n  <left>\n    <text>What about other mental illnesses apart from depression?</text>\n    <text>In the chart, you can see the population that was covered in data on other common mental illnesses.</text>\n    <text>As you can see, there was more data available on anxiety disorders and major depression than on schizophrenia and bipolar disorder.</text>\n    <text>You can click ‘Change country’ to see how this varies between world regions.</text>\n  </left>\n  <right>\n    <chart url="https://ourworldindata.org/grapher/adult-population-covered-in-primary-data-on-the-prevalence-of-mental-illnesses"/>\n  </right>\n</sticky-right>',
      },
    ],
  },
  "subscribe-banner": {
    count: 2,
    examples: [
      { slug: "introducing-new-search", gdocType: "article", xhtml: "<subscribe-banner/>" },
      {
        slug: "trade-and-globalization",
        gdocType: "linear-topic-page",
        xhtml: "<subscribe-banner/>",
      },
    ],
  },
  table: {
    count: 40,
    examples: [
      {
        slug: "how-do-statistical-organizations-define-age-periods-in-children",
        gdocType: "article",
        xhtml:
          "<table>\n  <row>\n    <cell>\n      <text>Age period</text>\n    </cell>\n    <cell>\n      <text>Definition</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Early neonatal</text>\n    </cell>\n    <cell>\n      <text>Under 7 days</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Late neonatal</text>\n    </cell>\n    <cell>\n      <text>7–27 days</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Neonatal</text>\n    </cell>\n    <cell>\n      <text>Under 28 days</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Post-neonatal</text>\n    </cell>\n    <cell>\n      <text>28 days to 1 year of age</text>\n    </cell>\n  </row>\n</table>",
      },
      {
        slug: "faq-on-plastics",
        gdocType: "article",
        xhtml:
          "<table>\n  <row>\n    <cell>\n      <text>\n        <b>Particle category</b>\n      </text>\n    </cell>\n    <cell>\n      <text>\n        <b>Diameter range</b>\n      </text>\n      <text>\n        <b>(mm = millimetres)</b>\n      </text>\n      <text></text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Nanoplastics</text>\n    </cell>\n    <cell>\n      <text>&lt; 0.0001 mm (0.1μm)</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Small microplastics</text>\n    </cell>\n    <cell>\n      <text>0.0001 – 1 mm</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Large microplastics</text>\n    </cell>\n    <cell>\n      <text>1 – 4.75 mm</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Mesoplastics</text>\n    </cell>\n    <cell>\n      <text>4.76 – 200 mm</text>\n    </cell>\n  </row>\n  <row>\n    <cell>\n      <text>Macroplastics</text>\n    </cell>\n    <cell>\n      <text>&gt;200 mm</text>\n    </cell>\n  </row>\n</table>",
      },
    ],
  },
  text: {
    count: 30919,
    examples: [
      {
        slug: "air-pollution-does-it-get-worse-before-it-gets-better",
        gdocType: "article",
        xhtml:
          '<text>The EKC provides a hypothesis of the link between environmental degradation and economic development: environmental quality initially worsens with the onset of industrial growth, but then peaks at a certain stage of economic development and from then on environmental quality begins to improve with increased development. Evidence of the EKC is very mixed: across various measures it has been widely contested, but for a number of environmental markers there is strong evidence for the existence of EKC relationship. For example, a recent study published in Science suggests the EKC relationship also appears in links between deforestation, afforestation and economic growth.\n  <ref url="#note-5">\n    <sup>5</sup>\n  </ref>\n</text>',
      },
      {
        slug: "the-our-world-in-data-dataset-of-famines",
        gdocType: "article",
        xhtml:
          '<text>In our table, we have excluded crises where reported excess mortality was lower than 1,000. Our reasons for doing so were twofold. First, in the context of very large margins of error for many of the famines in our table (with upper and lower estimates of excess mortality sometimes several million apart), we felt that including events in which very few people are recorded as dying might give a misleading impression of the accuracy of the rest of the estimates in the table. Second, for many people, substantial excess mortality (due to starvation or hunger-induced diseases) would normally be seen as an integral part of what it means for a crisis to constitute a famine.\n  <ref url="#note-7">\n    <sup>7</sup>\n  </ref>\n</text>',
      },
    ],
  },
  "topic-page-intro": {
    count: 64,
    examples: [
      {
        slug: "energy",
        gdocType: "topic-page",
        xhtml:
          '<topic-page-intro>\n  <download-button text="Download all data on energy" url="https://github.com/owid/energy-data"/>\n  <related-topics>\n    <topic url="https://ourworldindata.org/co2-and-other-greenhouse-gas-emissions" text="CO₂ and Greenhouse Gas Emissions"/>\n    <topic url="https://ourworldindata.org/air-pollution" text="Air Pollution"/>\n    <topic url="https://ourworldindata.org/oil-spills" text="Oil Spills"/>\n  </related-topics>\n  <content>\n    <text>The world \n      <a href="https://docs.google.com/document/d/14ZnX7uW1aOuJAM7CPFmxwdq8fniYwBqDfbp4mlS0ZZA/edit">lacks</a> a safe, low-carbon, and cheap large-scale energy infrastructure.\n    </text>\n    <text>Until we scale up such an energy infrastructure, the world will continue to face two energy problems: hundreds of millions of people lack access to sufficient energy, and the dominance of fossil fuels in our energy system drives \n      <a href="https://ourworldindata.org/co2-and-greenhouse-gas-emissions">climate change</a> and other health impacts such as \n      <a href="https://ourworldindata.org/air-pollution">air pollution</a>.\n    </text>\n    <text>To ensure everyone has access to clean and safe energy, we need to understand energy consumption and its impacts around the world today and how this has changed over time.</text>\n    <text>On this page, you can find all our data, visualizations, and writing relating to energy.</text>\n  </content>\n</topic-page-intro>',
      },
      {
        slug: "migration",
        gdocType: "topic-page",
        xhtml:
          '<topic-page-intro>\n  <related-topics>\n    <topic url="https://ourworldindata.org/world-population-growth" text="World Population Growth"/>\n    <topic url="https://ourworldindata.org/poverty" text="Poverty"/>\n    <topic url="https://ourworldindata.org/income-inequality" text="Income inequality"/>\n  </related-topics>\n  <content>\n    <text>Hundreds of millions of people live in a country that is different from the one in which they were born. In some countries, the majority of the population are immigrants.</text>\n    <text>Migration has played a crucial role in economic development, education and mobility. The transfer of money from migrants working overseas to family or friends in their home country – remittances – can be an important \n      <a href="http://ourworldindata.org/economic-growth">source of income</a> in many countries.\n    </text>\n    <text>On this page you can find our writing and data visualizations relating to migration.</text>\n  </content>\n</topic-page-intro>',
      },
    ],
  },
  video: {
    count: 26,
    examples: [
      {
        slug: "owid-covid-history",
        gdocType: "article",
        xhtml:
          '<video url="https://assets.ourworldindata.org/videos/OWID-coronavirus-data-explorer-15-5-2020.mp4" filename="OWID-coronavirus-data-explorer-15-5-2020-frame.png" shouldLoop="true" shouldAutoplay="true">\n  <caption>Screen-capture video of the earliest version of Our World in Data’s COVID-19 data explorer, \n    <a href="https://x.com/MaxCRoser/status/1261095575715528705">launched</a> on May 15, 2020. The video runs through different indicators and features in the data explorer. The current version of the Explorer can be viewed \n    <a href="https://ourworldindata.org/explorers/covid">online</a>.\n  </caption>\n</video>',
      },
      {
        slug: "what-no-safe-water-means",
        gdocType: "article",
        xhtml:
          '<video url="https://assets.ourworldindata.org/videos/drinking-water-burundi-video.mp4" filename="drinking-water-burundi-poster.webp" shouldLoop="true" shouldAutoplay="false">\n  <caption>Source: Johan Eriksson for Dollar Street 2015 (Free to use under CC BY 4.0)</caption>\n</video>',
      },
    ],
  },
};
