# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:13
from __future__ import unicode_literals
from django.db import migrations, models, transaction
import json

def tweak_selectedEntities(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            config = json.loads(chart.config)
            
            for axisName in ['x', 'y']:
                axis = {}
                old = config.get(axisName+'-axis', None)
                if not isinstance(old, dict):
                    old = {}
                
                label = old.get('axis-label', None)
                if isinstance(label, str) and len(label) > 0:
                    axis['label'] = label

                prefix = old.get('axis-prefix', None)
                if isinstance(prefix, str) and len(prefix) > 0:
                    axis['prefix'] = prefix

                suffix = old.get('axis-suffix', None)
                if isinstance(suffix, str) and len(suffix) > 0:
                    axis['suffix'] = suffix

                try:
                    axis['min'] = float(old.get('axis-min', None))
                except (TypeError, ValueError):
                    pass
                try:
                    axis['max'] = float(old.get('axis-max', None))
                except (TypeError, ValueError):
                    pass

                scaleType = old.get('axis-scale', 'linear')
                if scaleType == 'log':
                    axis['scaleType'] = 'log'
                else:
                    axis['scaleType'] = 'linear'

                if config.get(axisName + "-axis-scale-selector", False):
                    axis['canChangeScaleType'] = True

                try:
                    axis['numDecimalPlaces'] = float(old.get('axis-format', None))
                except (TypeError, ValueError):
                    pass

                if old.get("axis-label-distance"):
                    axis['labelDistance'] = float(old.get("axis-label-distance"))
                    

                print(axisName)
                print(old)
                print(axis)
                print()
                config[axisName+'Axis'] = axis
                if axisName+'-axis' in config:
                    del config[axisName+'-axis']
                if axisName+'-axis-scale-selector' in config:
                    del config[axisName+'-axis-scale-selector']

            chart.config = json.dumps(config)
            chart.save()

class Migration(migrations.Migration):
    dependencies = [
        ('grapher_admin', '0003_auto_20170602_0413'),
    ]
    operations = [
        migrations.RunPython(tweak_selectedEntities),
    ]