# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0003_auto_20170602_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_info',
            field=models.TextField(null=True),
        ),
    ]
