# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:13
from __future__ import unicode_literals
from django.db import migrations, models, transaction
import json

def tweak_selectedEntities(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            config = json.loads(chart.config)
            
            for axisName in ['x', 'y']:
                axis = {}
                old = config[axisName+'-axis']
                if not isinstance(axis, dict):
                    old = {}
                axis['label'] = old.get("axis-label", "")
                axis['min'] = None if old.get("axis-min", None) is None else float(old['axis-min'])
                axis['max'] = None if old.get("axis-max", None) is None else float(old['axis-max'])

#                            label: yAxis["axis-label"],
#            min: yAxis["axis-min"],
#            max: yAxis["axis-max"],
#            prefix: yAxis["axis-prefix"],
#            suffix: yAxis["axis-suffix"],
#            scaleType: yAxis["axis-scale"],
#            canChangeScaleType: this.model.get("y-axis-scale-selector"),
#            numDecimalPlaces: yAxis["axis-format"]


            print(config['x-axis'])

            chart.config = json.dumps(config)
#                chart.save()
    import sys
    sys.exit(1)

class Migration(migrations.Migration):
    dependencies = [
        ('grapher_admin', '0003_auto_20170602_0413'),
    ]
    operations = [
        migrations.RunPython(tweak_selectedEntities),
    ]