# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:13
from __future__ import unicode_literals
from django.db import migrations, models, transaction
import json

def selectedKeysRedesign(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            config = json.loads(chart.config)

            

            chart.config = json.dumps(config)
            chart.save()

class Migration(migrations.Migration):
    dependencies = [
        ('grapher_admin', '0004_axis_config_cleanup.py'),
    ]
    operations = [
        migrations.RunPython(selectedKeysRedesign),
    ]