# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0004_datasetcategory_fetcher_autocreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCommitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_date', models.DateTimeField()),
                ('commit_hash', models.CharField(max_length=255, unique=True)),
                ('commit_made_by', models.CharField(max_length=255, null=True)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grapher_admin.Dataset')),
            ],
            options={
                'db_table': 'dataset_commit_history',
            },
        ),
    ]
