# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0004_datasetcategory_fetcher_autocreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='short_unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
