# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0005_selected_keys_redesign'),
        ('grapher_admin', '0005_auto_20170720_1410'),
    ]

    operations = [
    ]
