# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0006_auto_20170711_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='short_unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
