# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 09:48
from __future__ import unicode_literals
from django.db import migrations, models, transaction
import json

def migrate(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    Variable = apps.get_model('grapher_admin', 'Variable')
    with transaction.atomic():
        for chart in Chart.objects.all():
            config = json.loads(chart.config)
            
            if 'chart-dimensions' in config:
                if not 'dimensions' in config:
                    config['dimensions'] = config['chart-dimensions']
                del config['chart-dimensions']
            
            chart.config = json.dumps(config)
            chart.save()





class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0009_fix_map_colorSchemeValuesAutomatic'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
