# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 03:30
from __future__ import unicode_literals

from django.db import migrations


def change_un_wpp_source_names(apps, schema_editor):
    # The current names of UN WPP dataset sources are too long and confusing
    # We will change these source names to United Nations – Population Division (2017 Revision)
    Source = apps.get_model('grapher_admin', 'Source')
    Dataset = apps.get_model('grapher_admin', 'Dataset')
    all_un_wpp_sources = Source.objects.filter(datasetId__in=Dataset.objects.filter(namespace__contains='unwpp'))
    for each in all_un_wpp_sources:
        each.name = 'United Nations – Population Division (2017 Revision)'
        each.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0010_auto_20170911_1454'),
    ]

    operations = [
        migrations.RunPython(change_un_wpp_source_names),
    ]
