# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0010_rename_dimensions_20170913_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdimension',
            name='conversionFactor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
