# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0011_chartdimension_conversionfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='displayIsProjection',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='variable',
            name='displayName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='displayShortUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='displayTolerance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='displayUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='displayUnitConversionFactor',
            field=models.FloatField(null=True),
        ),
    ]
