# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0012_auto_20170914_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdimension',
            name='color',
        ),
        migrations.AddField(
            model_name='chartdimension',
            name='shortUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartdimension',
            name='conversionFactor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chartdimension',
            name='displayName',
            field=models.CharField(db_column='displayName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chartdimension',
            name='isProjection',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='chartdimension',
            name='tolerance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chartdimension',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
