# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0013_auto_20170914_0741'),
        ('grapher_admin', '0011_auto_20170912_0330'),
    ]

    operations = [
    ]
