# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0016_remove_old_axis_labels_20170915_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdimension',
            name='conversionFactor',
            field=models.FloatField(null=True),
        ),
    ]
