# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 20:45
from __future__ import unicode_literals
from django.db import migrations, models, transaction
import json

def migrate(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            config = json.loads(chart.config)

            if 'map' in config and config.get('map'):
                mapConfig = config['map']
                if 'variableId' in mapConfig:
                    mapConfig['variableId'] = int(mapConfig['variableId'])
            
            chart.config = json.dumps(config)
            chart.save()

class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0019_auto_20170925_1409'),
    ]

    operations = [
        migrations.RunPython(migrate),
    ]
