# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 14:32
from __future__ import unicode_literals
from django.db import migrations, models, transaction
import json

def canFloat(v):
    try:
        float(v)
    except Exception:
        return False

    return True

def execute(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            config = json.loads(chart.config)
            if not 'map' in config:
                continue

            if 'colorSchemeMinValue' in config['map']:
                if config['map']['colorSchemeMinValue'] is None or config['map']['colorSchemeMinValue'] == "":
                    del config['map']['colorSchemeMinValue']
                else:
                    config['map']['colorSchemeMinValue'] = float(config['map']['colorSchemeMinValue'])
            if 'colorSchemeValues' in config['map']:
                if type(config['map']['colorSchemeValues']) is not list:
                    del config['map']['colorSchemeValues']
                else:
                    config['map']['colorSchemeValues'] = [float(v) for v in config['map']['colorSchemeValues'] if canFloat(v)]

            chart.config = json.dumps(config)
            chart.save()

class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0021_auto_20171023_1501'),
    ]

    operations = [
        migrations.RunPython(execute),
    ]
