# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 23:33
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0022_map_type_standardization_20171128_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='config',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
