# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 23:02
from __future__ import unicode_literals
from django.db import migrations, models, transaction, connection
import json

def execute(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            if chart.config['type'] == "ScatterPlot" or chart.config['type'] == "SlopeChart":
                properties = [d['property'] for d in chart.config['dimensions']]
                if not "color" in properties:
                    chart.config['dimensions'].append({ "variableId": 123, "property": "color" })
                if not "size" in properties:
                    chart.config['dimensions'].append({ "variableId": 72, "property": "size" })
                
            chart.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0023_auto_20171212_2333'),
    ]

    operations = [
        migrations.RunPython(execute),
    ]

