# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 11:24
from __future__ import unicode_literals

from django.db import migrations, transaction

def execute(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    Variable = apps.get_model('grapher_admin', 'Variable')
    ChartDimension = apps.get_model('grapher_admin', 'ChartDimension')
    with transaction.atomic():
        for chart in Chart.objects.all():
            for each in ChartDimension.objects.filter(chartId=chart.pk):
                each.delete()

            for i, dim in enumerate(chart.config["dimensions"]):
                variable = Variable.objects.get(id=dim["variableId"])

                newdim = ChartDimension()
                newdim.chartId = chart
                newdim.variableId = variable
                newdim.property = dim.get('property', None)
                newdim.order = i

                newdim.displayName = dim.get('displayName', None)
                newdim.unit = dim.get('unit', None)
                newdim.shortUnit = dim.get('shortUnit', None)
                newdim.conversionFactor = dim.get('conversionFactor', None)
                newdim.tolerance = dim.get('tolerance', None)
                newdim.isProjection = dim.get('isProjection', None)
                newdim.targetYear = dim.get('targetYear', None)
                newdim.save()

class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0024_auto_20171221_2302'),
    ]

    operations = [
        migrations.RunPython(execute)
    ]
