# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0025_auto_20180104_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='published_by',
            field=models.ForeignKey(blank=True, db_column='published_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='published_charts', to=settings.AUTH_USER_MODEL, to_field='name'),
        ),
    ]
