# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0028_auto_20180117_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudflarePurgeQueue',
        ),
        migrations.AddField(
            model_name='chartdimension',
            name='numDecimalPlaces',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='displayNumDecimalPlaces',
            field=models.IntegerField(null=True),
        ),
    ]
