# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0029_auto_20180201_0923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='chart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='origin_url',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='published',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='type',
        ),
    ]
