# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 00:21
from __future__ import unicode_literals
from django.db import migrations, models, transaction, connection

def execute(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            for dim in chart.config['dimensions']:
                display = {}
                if 'displayName' in dim:
                    display['name'] = dim.pop('displayName')
                if 'unit' in dim:
                    display['unit'] = dim.pop('unit')
                if 'shortUnit' in dim:
                    display['shortUnit'] = dim.pop('shortUnit')
                if 'isProjection' in dim:
                    display['isProjection'] = dim.pop('isProjection')
                if 'conversionFactor' in dim:
                    display['conversionFactor'] = dim.pop('conversionFactor')
                if 'tolerance' in dim:
                    display['tolerance'] = dim.pop('tolerance')
                dim['display'] = display

            chart.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0030_auto_20180215_2337'),
    ]

    operations = [
        migrations.RunPython(execute),
    ]
