# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0035_auto_20180216_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfile',
            name='fk_user_id',
        ),
        migrations.DeleteModel(
            name='InputFile',
        ),
    ]
