# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0036_auto_20180307_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
