# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0037_auto_20180308_0706'),
    ]

    operations = [
        migrations.RenameField('DataValue', 'fk_ent_id', 'entityId'),
        migrations.RenameField('DataValue', 'fk_var_id', 'variableId'),
        migrations.AlterField(
            model_name='datavalue',
            name='entityId',
            field=models.ForeignKey(db_column='entityId', on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='grapher_admin.Entity'),
        ),
        migrations.AlterField(
            model_name='datavalue',
            name='variableId',
            field=models.ForeignKey(db_column='variableId', on_delete=django.db.models.deletion.CASCADE,
                                    to='grapher_admin.Variable'),
        ),
    ]
