# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0038_run_with_fake_option'),
    ]

    operations = [
        migrations.RenameField('DatasetSubcategory', 'fk_dst_cat_id', 'categoryId'),
        migrations.RenameField('Dataset', 'fk_dst_cat_id', 'categoryId'),
    ]
