# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0038_auto_20180308_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavalue',
            name='entityId',
            field=models.ForeignKey(db_column='entityId', on_delete=django.db.models.deletion.DO_NOTHING, to='grapher_admin.Entity'),
        ),
    ]
