# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0040_auto_20180310_1517'),
    ]

    operations = [
        migrations.RenameField('Dataset', 'fk_dst_subcat_id', 'subcategoryId'),
    ]
