# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0042_auto_20180310_1733'),
    ]

    operations = [
        migrations.RenameField('Variable', 'fk_dst_id', 'datasetId'),
        migrations.RenameField('Variable', 'fk_var_type_id', 'variableTypeId'),
    ]
