# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0043_auto_20180310_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='datasetId',
            field=models.ForeignKey(db_column='datasetId', on_delete=django.db.models.deletion.CASCADE, to='grapher_admin.Dataset'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variableTypeId',
            field=models.ForeignKey(db_column='variableTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='grapher_admin.VariableType'),
        ),
    ]
