# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 17:59
from __future__ import unicode_literals

from django.db import migrations, transaction
import json

# Fix nulls in dimension display settings
def migrate(apps, schema_editor):
    Chart = apps.get_model('grapher_admin', 'Chart')
    with transaction.atomic():
        for chart in Chart.objects.all():
            for dim in chart.config['dimensions']:
                display = dim['display']
                for key in list(display.keys()):
                    if display[key] is None:
                        del display[key]
            
            chart.save()

class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0044_auto_20180310_1851'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
