# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0044_auto_20180310_1851'),
        ('grapher_admin', '0036_auto_20180216_0532'),
    ]

    operations = [
    ]
