# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher_admin', '0045_merge_20180314_1533'),
        ('grapher_admin', '0045_auto_20180315_1759'),
    ]

    operations = [
    ]
