<?php
 
use Illuminate\Database\Seeder;
 
class DatasetSubcategoriesTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('dataset_subcategories')->delete();
		
		//reset autoincrement
		$statement = "ALTER TABLE dataset_subcategories AUTO_INCREMENT = 1;";
		DB::unprepared($statement);
		
		$dataset_subcategories = array(
			
			[ 'name' => 'World Population', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'World Population Growth', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'World Fertility Rate, World Life Expectancy and Forecasts of World Population', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Pop.&PopDist of Single Countries', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'The Distribution of World Population', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Mortality Rates', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Fertility Rates', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Determinants of Fertility (Social and Individual)', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Population Growth & Demographic Transition', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Age Structure', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Vital Statistics Quality of Data & History', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Infant & Child Mortality', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Determinants of Child Mortality', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Life Expectancy', 'fk_dst_cat_id' => 1 ],
			[ 'name' => 'Survival Curves and Age-Specific Mortality', 'fk_dst_cat_id' => 1 ],

			[ 'name' => 'Maternal Health & Mortality', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Health Care, Doctors & Health Workers', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Health Spending & Price of Health & Insurance of Health', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Medical Research & Innovation', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Contraception & Abortions', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Teenage Marriage, Pregnancy', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Health in Global Perspective', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Hygiene', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Causes of Death', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Tuberculosis', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Cancer', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'HIV / AIDS & STIs', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Malaria', 'fk_dst_cat_id' => 2 ],
			[ 'name' => '(Neglected) Tropical Diseases', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Infectious Disease', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Noncommunicable Diseases', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Eradications of Diseases (Polio, Smallpox and more)', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Epidemics & Crises', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Disabilities & Chronic Diseases (Onset and Prevalence)', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'DALY Healthy Years of Live Years', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Dental Health', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Bones & Joints', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Plastic Surgery', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Human Genome', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Vaccination Coverage & Success', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Medicine & Pharmaceuticals', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Antibiotics (Price & Spread)', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Blood Donations', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Organ Donation', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Global Inequality of Health', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Within Society Inequality of Health', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Exposure to Toxins', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Suicides', 'fk_dst_cat_id' => 2 ],
			[ 'name' => 'Psychological Problems', 'fk_dst_cat_id' => 2 ],

			[ 'name' => 'Food Consumption – Food per Capita (kcal/person)', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Energy Requirements of Humans', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Hunger & Undernourishment — Quantitative Undernourishment / Malnourishment', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Famines', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Output & Productivity', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Output Agricultural Production & Food Availability', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Productivity (Output/Input) of Agriculture', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Agricultural Employment – Labor Use in Agriculture', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Land Use in Agriculture', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Yields, Seeds, Fertilizer and Pesticides', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Yields (quantity per area)', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Improved Seeds & GMO', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Fertilizer', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Pesticides', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Organic Farming', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Agricultural Research', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Irrigation of Land', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Soil Loss & Soil Quality', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Agricultural Subsidies & Tariffs', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Food Stocks', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Food Waste', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Food Prices', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Food Price Volatility & Food Trade', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Food Quality and Changing Food Consumption Basket', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Human Height', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Obesity & BMI', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Impact of Climate Change on Food Supply', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Farms & Agricultural Machinery', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Agricultural Machinery & Technology', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Farms', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Non-food Crops (Biofuels,..', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Drugs & Alcohol Consumption', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Smoking & Lung Cancer', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Marijuana', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Meat & Animals', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Productivity per animal', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Meat & Livestock Counts', 'fk_dst_cat_id' => 3 ],
			[ 'name' => 'Seafood', 'fk_dst_cat_id' => 3 ],
			
			[ 'name' => 'Forest Cover', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Land Cover, Land Use, & Primary Production', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Environmental Indices', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Environment <- Growth, Institutions', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Environmental Protection Efforts', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Public Opinion about Environment / Importance of Environmental Issues', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Natural Reserves & Parks', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Biodiversity', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Extinction & Recovery of Animals', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Environment -> Health', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Water Accessibility & Consumption / Sanitation', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Water Quality in Rivers and Oceans', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Acid Rain', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Ozone Layer', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Air Pollution', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Indoor Air (Cooking)', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Waste', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Natural Catastrophes (Victims & Costs)', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Climate Change', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Climate Change & Consequences', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Public Views on Climate Change', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Past Climate Issues (Heat and Cold related Deaths, Floods)', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Carbon Stocks', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Mitigation of Climate Change', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Energy', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Energy Production & Consumption', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Electricity', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Co2/Greenhouse Gas Emissions and Energy Sources', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Renewable Energy', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Price of Energy', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Trade in Energy', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Change of Energy Sources', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Change of Energy Uses', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Nuclear Energy', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Nuclear Catastrophes & Safety of Different Forms of Energy Production', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Fossil Energy Resources (Gas, Coal, Uranium & others)', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Energy Efficiency', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Oil Price, Taxes, Production & Consumption', 'fk_dst_cat_id' => 4 ],
			[ 'name' => 'Non-Energy Resources', 'fk_dst_cat_id' => 4 ],

			[ 'name' => 'Space Travel & Satellites', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Patents & Innovation', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Computer', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Product Quality', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Moore’s Law & other Laws of Exponential Technological Progress', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Quality of Technology', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Risk of Accidents', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Poison in Products', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Risk of Fire', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Ephemeralization', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Chemicals Management & Catastrophes', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Technological Disasters', 'fk_dst_cat_id' => 5 ],
			[ 'name' => 'Transportation', 'fk_dst_cat_id' => 5 ],
			
			[ 'name' => 'Correlation of Economic Prosperity & x', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Growth of Global GDP per capita – over the last Millennia until Now', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'GDP Growth around the World – over the last 2000 years', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'GDP Growth in the last 200 years – Divergence and Catch-Up', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'GDP over the last 50 years', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Growth of Ex-DCs – Econ. Convergence between Countries', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'WID World Income Distribution & GDP Distribution Maps', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Predictions of Global Growth', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Geographic Distribution of Prosperity', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Drivers of Growth and G. Accounts', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Wages', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Real Prices – Productivity Increase', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Inflation – Price Indices', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Consumption Basket', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Online Shopping', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Inequality of Income', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Inequality of Wealth', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Income Mobility & Social Mobility', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Inequality of QoL (<-Income Inequality)', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Low Incomes in ICs & Relative Poverty', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Econ Gender & Race Dif (in Wage & Labor)', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Econ Gender Dif (in Wage & Labor)', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Econ Race Dif (in Wage & Labor)', 'fk_dst_cat_id' => 6 ],
			[ 'name' => '(Global) Poverty', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Poverty in single countries', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Middle Class', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Factor Incomes', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Business Cycles, Crises & Recessions', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Financial Stability', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Interest Rate & Credit Market', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Corporate Profits', 'fk_dst_cat_id' => 6 ],
			[ 'name' => 'Consumer Credit & Debt', 'fk_dst_cat_id' => 6 ],
			
			[ 'name' => 'Happiness & Life Satisfaction', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'HDI', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Aggregated Indicators', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Quality of Life / Standard of Living', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'QOL Convergence — Global Convergence of Quality of Life', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Proxies for Standard of Living – Light from Satellites', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Goods (Clothes, Household items)', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Quality of Housing', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Housing, House Size', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'Homelessness', 'fk_dst_cat_id' => 7 ],
			[ 'name' => 'MDG (Millenium Development Goals)', 'fk_dst_cat_id' => 7 ],

			[ 'name' => 'Productivity of Technologies', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Productivity (Efficiency) and Growth', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Industrialization & Technological Progress', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Capital Formation & Investment', 'fk_dst_cat_id' => 8 ],
			[ 'name' => '3 Economic Sectors – Occupations', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Economies based on Primary Goods', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Resource Rents & Curse', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Finance & Stock', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Banks & Financial Institutions', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Finance & Business Education', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Capital per Worker', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Strikes / Industrial Disputes', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Corruption', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Working Hours per Week', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Working Hours over Live', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Holiday', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Job Satisfaction', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Use of Time', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Risk', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Work Conditions & Safety', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Changes in the labour market', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Worker Organization (Unions)', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Workers Rights', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Child Labour', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Slavery', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Servants', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Property Rights & Economic Freedom', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Labor Force Participation (by Gender and Age)', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Start-Up & Entrepeneurial', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Unemployment & (Un)employment Policy', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Monetary Systems', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Monetary Policy', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Money Supply', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Voluntary Work', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Open-Source', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Charitable Giving', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Non-Profit Sector', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Views on Capitalism', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Economic Systems (Capitalism, Communism)', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Economic Freedom', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Economic Regulation', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Competition', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Property Rights', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'Urbanisation', 'fk_dst_cat_id' => 8 ],
			[ 'name' => 'QoL in City and Rural parts', 'fk_dst_cat_id' => 8 ],

			[ 'name' => 'Taxes and Government Revenues', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Income Taxes', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Corporate Tax', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Tax Havens', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Government Spending', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Government Employment', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Social Spending & Social Protection', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Redistribution', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Pension system / Incomes of the old', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Public Debt & Gov Bonds', 'fk_dst_cat_id' => 9 ],
			[ 'name' => 'Labour Market Policy', 'fk_dst_cat_id' => 9 ],
			
			[ 'name' => 'Intergovernmental Organisations & Diplomacy', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'State Unions (supranational)', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Economic Unions', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Trade – from Antiquity to Early Modern Times', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Trade – over the recent past to the Present', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Trade Composition', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Tariffs, Financial Liberalisation & Trade Barriers', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'ToT – Terms of Trade', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Exchange Rates & Currencies', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'FDI & Capital Flows', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Capital Accounts', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Foreign Aid & ODA & Food Aid', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Trends in Africa', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Trends for the bottom billion', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Traveling & Tourism', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Freedom to Travel', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Remittances', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Migration', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Binnenmigration', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Education & Migration', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Forced Migration', 'fk_dst_cat_id' => 10 ],
			[ 'name' => 'Political Asylum & Refugees', 'fk_dst_cat_id' => 10 ],

			[ 'name' => 'Wars before 1945', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Wars after 1945', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Civil Wars', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Genocides', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Violence against the Political System (Coups / Regicide etc.', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Terrorism', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Fortifications of Settlements', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Peacekeeping', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Military Spending', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Arms Producers, Trade & Non-Proliferation', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Nuclear Weapons', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Military Personnel & Conscription', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Consequences of Conflict', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Costs of Wars', 'fk_dst_cat_id' => 11 ],
			[ 'name' => 'Correlates & Drivers of Peace', 'fk_dst_cat_id' => 11 ],
			
			[ 'name' => 'Democratisation', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Quality of Democracy – Accountability & Transperancy', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Trust in Political Regime & Institutions', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Determinants of Democratisation (Education & Economic Prosperity)', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Extension of Franchise', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Turnout', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Political Engagement etc', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Political Engagement & Protest', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Seperation of State and Religion', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Political Stability & Coups', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Gender Dif in Politics', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Protests', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Rule of Law', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Colonialism & Imperialism', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Empires', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Opinion Polls on Political Regimes', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Single Politicians/Governments', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Violence from Political Regimes', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Death Penalty', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Judicial Torture', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Prisons & Police', 'fk_dst_cat_id' => 12 ],
			[ 'name' => 'Privacy & Surveillance', 'fk_dst_cat_id' => 12 ],

			[ 'name' => 'Violent Deaths in Pre-state Societies – Ethnographic and Archaeological Evidence on Violent Deaths', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'pre 1800 Time-Series Murder Rates', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'post 1800 Time-Series Murder Rates', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Homicide Rates by Gender & Age – Correlation of Homicide & other Violence', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Guns', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Crime & Violence', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Cascade of Rights: Civil, Women, Children, Homosexuality, Animal', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Political Rights / Civil Rights', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Freedom of Religion, Religious Violence & Tolerance', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Treatment of Minorities – Violence and Tolerance', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Gender Equality – Women – Violence against & Rights for', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Rape', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Genital Mutilation', 'fk_dst_cat_id' => 13 ],
			[ 'name' => '‘Missing Women’ (Gender-biased Infanticide & Gender Ratios)', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Gender Ratio', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Domestic Violence', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Children – Violence against & Rights for', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Homosexuals Violence against & Rights for', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Animals – Violence against & Rights for', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Vegetarianism', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Infanticide', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Treatment of the Elderly', 'fk_dst_cat_id' => 13 ],
			[ 'name' => 'Freedom of Press & Speech', 'fk_dst_cat_id' => 13 ],
			
			[ 'name' => 'Correlations of Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Global Rise of Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Projections of Future Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Financing of Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Literacy', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Numeracy', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Pre-Primary Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Schools & Basic Education (Primary)', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Secondary Schools', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Tertiary Education – Monasteries to Unis', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Lifelong Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'R&D, Engineers & Scientists', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Quality of Education & Drop-Out Rates', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Test Scores & Quality of Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Drop Out Rates', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Teachers & Professors', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Income<->Education and Education Mobility', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Time spend studying', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Skill Premium – Income by Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Inequality of Education (incl. Gender & Race)', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Gender Dif in Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Race Dif in Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Inequality of Education', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Internat. Research Community', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Open-Data etc.', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Intelligence / Flynn-Effekt', 'fk_dst_cat_id' => 14 ],
			[ 'name' => 'Knowledge / Scientometrics', 'fk_dst_cat_id' => 14 ],

			[ 'name' => 'Book Production, Prices & Consumption', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'Internet & Media today', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'Social Media', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'Theater, Music, Zoo, Museum etc.', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'News & Public Media', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'Reporting of the Media', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'TV & Movie', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'Music', 'fk_dst_cat_id' => 15 ],
			[ 'name' => 'Communication Technology & Mobile Phone', 'fk_dst_cat_id' => 15 ],
			
			[ 'name' => 'Values to Self Expression & Secular-Rational', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Surv vs. Self Ex & Trad vs. Secular-Rational', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Life Goals', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Demand for Rights & Liberty', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Materialism & Postmaterialism', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Rational Orientation – Views on Science and Education', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Individualism', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'We-Feeling, Nationalism & Cosmopolitanism', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Value Determinants', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Optimism & Pessimism – Forward Looking – Perception of Way of the World', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Conservativism vs Liberalism', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Trust', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Variety', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Culture contact & transfers', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'World Languages', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Fragmentazation & Segregation', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Sports', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Religion', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Atheism', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Sex', 'fk_dst_cat_id' => 16 ],
			[ 'name' => 'Marriage & Relationships', 'fk_dst_cat_id' => 16 ],

		);
		
		// Uncomment the below to run the seeder
		DB::table('dataset_subcategories')->insert($dataset_subcategories);
	}

}

?>