// Misc non-SPA views
import { Request, Response, Router } from "express"
import * as express from "express"
import rateLimit from "express-rate-limit"
import filenamify from "filenamify"
import React from "react"
import { Writable } from "stream"
import { expectInt, renderToHtmlPage } from "../serverUtils/serverUtil.js"
import { logInWithCredentials, logOut } from "./authentication.js"
import { LoginPage } from "./LoginPage.js"
import * as db from "../db/db.js"
import { Dataset } from "../db/model/Dataset.js"
import { ENV } from "../settings/serverSettings.js"
import { ExplorerAdminServer } from "../explorerAdminServer/ExplorerAdminServer.js"
import {
    renderExplorerPage,
    renderGdocsArticle,
    renderPreview,
} from "../baker/siteRenderers.js"
import { GitCmsServer } from "../gitCms/GitCmsServer.js"
import { GIT_CMS_DIR } from "../gitCms/GitCmsConstants.js"
import {
    OwidArticleType,
    parseIntOrUndefined,
    slugify,
    stringifyUnkownError,
} from "@ourworldindata/utils"
import {
    DefaultNewExplorerSlug,
    EXPLORERS_PREVIEW_ROUTE,
    GetAllExplorersRoute,
} from "../explorer/ExplorerConstants.js"
import {
    ExplorerProgram,
    EXPLORER_FILE_SUFFIX,
} from "../explorer/ExplorerProgram.js"
import { existsSync } from "fs-extra"
import * as Post from "../db/model/Post.js"

// Used for rate-limiting important endpoints (login, register) to prevent brute force attacks
const limiterMiddleware = (
    onFailRender: (req: Request, res: Response) => React.ReactElement
) =>
    rateLimit({
        windowMs: 60_000, // 1 minute
        max: 10, // max. 10 requests per minute
        handler: (req, res) =>
            res.status(429).send(renderToHtmlPage(onFailRender(req, res))),
    })

const adminRouter = Router()

// Parse incoming requests with JSON payloads http://expressjs.com/en/api.html
adminRouter.use(express.json({ limit: "50mb" }))

// None of these should be google indexed
adminRouter.use(async (req, res, next) => {
    res.set("X-Robots-Tag", "noindex")
    return next()
})

adminRouter.get("/", async (req, res) => {
    // Preview URLs generated by WP depend on the status of the post:
    // * PUBLISHED: owid.cloud/SLUG?preview=true --> run through WP singular.php
    //   and directly redirected to /admin/posts/preview/POST_ID
    // * DRAFT:
    //     - post: owid.cloud/?p=POST_ID&preview=true
    //     - page: owid.cloud/?page_id=PAGE_ID&preview=true
    //   --> "/" captured by NGINX and redirected here (/admin/)
    //
    // Ideally, the preview URL in WP would be pointing directly to
    // /admin/posts/preview/POST_ID (bypassing WP altogether, for published and
    // draft posts) but this is only partially possible for now, as the preview
    // URL of draft posts does not get rewritten by the preview_post_link filter
    // within Gutenberg.
    //
    // See:
    //  * https://github.com/WordPress/gutenberg/issues/13998
    //  * https://developer.wordpress.org/reference/hooks/preview_post_link/
    if (req.query.preview === "true" && (req.query.p || req.query.page_id)) {
        // HACK
        res.redirect(`/admin/posts/preview/${req.query.p || req.query.page_id}`)
    } else {
        res.redirect(`/admin/charts`)
    }
})

adminRouter.get("/login", async (req, res) => {
    res.send(renderToHtmlPage(<LoginPage next={req.query.next as string} />))
})
adminRouter.post(
    "/login",
    limiterMiddleware((req) => (
        <LoginPage
            errorMessage="Too many attempts, please try again in a minute."
            next={req.query.next as string}
        />
    )),
    async (req, res) => {
        try {
            const session = await logInWithCredentials(
                req.body.username,
                req.body.password
            )
            res.cookie("sessionid", session.id, {
                httpOnly: true,
                sameSite: "lax",
                secure: ENV === "production",
            })
            res.redirect((req.query.next as string) || "/admin")
        } catch (err) {
            res.status(400).send(
                renderToHtmlPage(
                    <LoginPage
                        next={req.query.next as string}
                        errorMessage={stringifyUnkownError(err)}
                    />
                )
            )
        }
    }
)

adminRouter.get("/logout", logOut)

adminRouter.get("/datasets/:datasetId.csv", async (req, res) => {
    const datasetId = expectInt(req.params.datasetId)

    const datasetName = (
        await db.mysqlFirst(`SELECT name FROM datasets WHERE id=?`, [datasetId])
    ).name
    res.attachment(filenamify(datasetName) + ".csv")

    const writeStream = new Writable({
        write(chunk, encoding, callback) {
            res.write(chunk.toString())
            callback(null)
        },
    })
    await Dataset.writeCSV(datasetId, writeStream)
    res.end()
})

adminRouter.get("/datasets/:datasetId/downloadZip", async (req, res) => {
    const datasetId = expectInt(req.params.datasetId)

    res.attachment("additional-material.zip")

    const file = await db.mysqlFirst(
        `SELECT filename, file FROM dataset_files WHERE datasetId=?`,
        [datasetId]
    )
    res.send(file.file)
})

adminRouter.get("/posts/preview/:postId", async (req, res) => {
    const postId = expectInt(req.params.postId)

    res.send(await renderPreview(postId))
})

adminRouter.get("/posts/compare/:postId", async (req, res) => {
    const postId = expectInt(req.params.postId)

    const wpPage = await renderPreview(postId)
    const archieMlText = await Post.select("archieml").from(
        db.knexTable(Post.postsTable).where({ id: postId })
    )
    const archieMl = JSON.parse(archieMlText[0].archieml) as OwidArticleType
    console.log("", archieMl.publishedAt)
    const archieMlPage = renderGdocsArticle(archieMl)

    res.send(`<!doctype html>
    <html>
        <head>
        </head>
        <body>
            <div style="width: 50%; float: left;">
                <h1>WP</h1>
                <iframe srcdoc="${wpPage.replaceAll(
                    '"',
                    "&quot;"
                )}" style="width: 100%; height: 100vh;"></iframe>
            </div>
            <div style="width: 50%; float: left;">
                <h1>ArchieML</h1>
                <iframe srcdoc="${archieMlPage.replaceAll(
                    '"',
                    "&quot;"
                )}" style="width: 100%; height: 100vh;"></iframe>
            </div>
        </body>
    </html>`)
})

adminRouter.get("/errorTest.csv", async (req, res) => {
    // Add `table /admin/errorTest.csv?code=404` to test fetch download failures
    const code = parseIntOrUndefined(req.query.code as string) ?? 400

    res.status(code)

    return `Simulating code ${code}`
})

const explorerAdminServer = new ExplorerAdminServer(GIT_CMS_DIR)

adminRouter.get(`/${GetAllExplorersRoute}`, async (req, res) => {
    res.send(await explorerAdminServer.getAllExplorersCommand())
})

adminRouter.get(`/${EXPLORERS_PREVIEW_ROUTE}/:slug`, async (req, res) => {
    const slug = slugify(req.params.slug)
    const filename = slug + EXPLORER_FILE_SUFFIX
    if (slug === DefaultNewExplorerSlug)
        return res.send(
            await renderExplorerPage(
                new ExplorerProgram(DefaultNewExplorerSlug, "")
            )
        )
    if (!slug || !existsSync(explorerAdminServer.absoluteFolderPath + filename))
        return res.send(`File not found`)
    const explorer = await explorerAdminServer.getExplorerFromFile(filename)
    return res.send(await renderExplorerPage(explorer))
})

const gitCmsServer = new GitCmsServer({
    baseDir: GIT_CMS_DIR,
    shouldAutoPush: true,
})
gitCmsServer.createDirAndInitIfNeeded()
gitCmsServer.addToRouter(adminRouter)

export { adminRouter }
