image: gitpod/workspace-mysql

ports:
    # express server
    - port: 3030
      onOpen: open-browser
    # mysql server
    - port: 3306
      onOpen: ignore
    - port: 33060
      onOpen: ignore
    # vite server
    - port: 8090
      onOpen: ignore

tasks:
    # set everything up
    # this is run in the prebuild state and should be ready when launching a new workspace
    - init: |
          gp await-port 3306 && ./db/downloadAndCreateDatabase.sh
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '';"
          nvm install
          npm install -g yarn
          yarn install
          cp .env.example .env && echo $'\n' >> .env
          tsc -b
          gp sync-done initial-setup
      # setting env variables required for Gitpod, because it doesn't run on localhost
      command: |
          echo VITE_DEV_URL=$(gp url 8090) >> .env
          echo BAKED_BASE_URL=$(gp url 3030) >> .env
          echo ADMIN_BASE_URL=$(gp url 3030) >> .env
    # wait for initial-setup (above) to finish and then start vite server
    - init: gp sync-await initial-setup
      command: yarn startViteServer
    # wait for initial-setup (above) to finish and then start admin server
    - init: gp sync-await initial-setup
      command: yarn startAdminDevServer

github:
    prebuilds:
        branches: true
        pullRequests: true
        addCheck: false

vscode:
    extensions:
        - dbaeumer.vscode-eslint
        - esbenp.prettier-vscode
