compressionLevel: mixed

enableGlobalCache: false

logFilters:
    - code: YN0013
      level: discard

nodeLinker: node-modules
npmMinimalAgeGate: 1440 # 24 hours
npmPreapprovedPackages:
    - react
    - react-dom
    - typescript
    - vite
    - vitest
