approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0013
    level: discard

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 72h
