// Misc non-SPA views
import { Request, Response, Router } from "express"
import rateLimit from "express-rate-limit"
import filenamify from "filenamify"
import * as React from "react"
import { getConnection } from "typeorm"

import * as db from "db/db"
import {
    expectInt,
    tryInt,
    renderToHtmlPage,
    JsonError,
} from "serverUtils/serverUtil"
import { logInWithCredentials, logOut } from "./utils/authentication"
import { LoginPage } from "./pages/LoginPage"
import { RegisterPage } from "./pages/RegisterPage"
import { Dataset } from "db/model/Dataset"

import { User } from "db/model/User"
import { UserInvitation } from "db/model/UserInvitation"
import { renderPreview } from "site/server/siteRenderers"
import { ENV } from "settings"
import { addExplorerAdminRoutes } from "explorer/admin/ExplorerBaker"

// Used for rate-limiting important endpoints (login, register) to prevent brute force attacks
const limiterMiddleware = (
    onFailRender: (req: Request, res: Response) => React.ReactElement
) =>
    rateLimit({
        windowMs: 60_000, // 1 minute
        max: 10, // max. 10 requests per minute
        handler: (req, res) =>
            res.status(429).send(renderToHtmlPage(onFailRender(req, res))),
    })

const adminRouter = Router()

// None of these should be google indexed
adminRouter.use(async (req, res, next) => {
    res.set("X-Robots-Tag", "noindex")
    return next()
})

adminRouter.get("/", async (req, res) => {
    // Preview URLs generated by WP depend on the status of the post:
    // * PUBLISHED: owid.cloud/SLUG?preview=true --> run through WP singular.php
    //   and directly redirected to /admin/posts/preview/POST_ID
    // * DRAFT:
    //     - post: owid.cloud/?p=POST_ID&preview=true
    //     - page: owid.cloud/?page_id=PAGE_ID&preview=true
    //   --> "/" captured by NGINX and redirected here (/admin/)
    //
    // Ideally, the preview URL in WP would be pointing directly to
    // /admin/posts/preview/POST_ID (bypassing WP altogether, for published and
    // draft posts) but this is only partially possible for now, as the preview
    // URL of draft posts does not get rewritten by the preview_post_link filter
    // within Gutenberg.
    //
    // See:
    //  * https://github.com/WordPress/gutenberg/issues/13998
    //  * https://developer.wordpress.org/reference/hooks/preview_post_link/
    if (req.query.preview === "true" && (req.query.p || req.query.page_id)) {
        // HACK
        res.redirect(`/admin/posts/preview/${req.query.p || req.query.page_id}`)
    } else {
        res.redirect(`/admin/charts`)
    }
})

adminRouter.get("/login", async (req, res) => {
    res.send(renderToHtmlPage(<LoginPage next={req.query.next} />))
})
adminRouter.post(
    "/login",
    limiterMiddleware((req) => (
        <LoginPage
            errorMessage="Too many attempts, please try again in a minute."
            next={req.query.next}
        />
    )),
    async (req, res) => {
        try {
            const session = await logInWithCredentials(
                req.body.username,
                req.body.password
            )
            res.cookie("sessionid", session.id, {
                httpOnly: true,
                sameSite: "lax",
                secure: ENV === "production",
            })
            res.redirect(req.query.next || "/admin")
        } catch (err) {
            res.status(400).send(
                renderToHtmlPage(
                    <LoginPage
                        next={req.query.next}
                        errorMessage={err.message}
                    />
                )
            )
        }
    }
)

adminRouter.get("/logout", logOut)

adminRouter.get(
    "/register",
    limiterMiddleware((req) => (
        <RegisterPage
            errorMessage="Too many attempts, please try again in a minute."
            body={req.query}
        />
    )),
    async (req, res) => {
        if (res.locals.user) {
            res.redirect("/admin")
            return
        }

        let errorMessage: string | undefined
        let invite: UserInvitation | undefined
        try {
            // Delete all expired invites before continuing
            await UserInvitation.createQueryBuilder()
                .where("validTill < NOW()")
                .delete()
                .execute()

            invite = await UserInvitation.findOne({ code: req.query.code })
            if (!invite) {
                throw new JsonError("Invite code invalid or expired")
            }
        } catch (err) {
            errorMessage = err.message
            res.status(tryInt(err.code, 500))
        } finally {
            res.send(
                renderToHtmlPage(
                    <RegisterPage
                        inviteEmail={invite && invite.email}
                        errorMessage={errorMessage}
                        body={req.query}
                    />
                )
            )
        }
    }
)

adminRouter.post(
    "/register",
    limiterMiddleware((req) => (
        <RegisterPage
            errorMessage="Too many attempts, please try again in a minute."
            body={req.query}
        />
    )),
    async (req, res) => {
        try {
            // Delete all expired invites before continuing
            await UserInvitation.createQueryBuilder()
                .where("validTill < NOW()")
                .delete()
                .execute()

            const invite = await UserInvitation.findOne({ code: req.body.code })
            if (!invite) {
                throw new JsonError("Invite code invalid or expired", 403)
            }

            if (req.body.password !== req.body.confirmPassword) {
                throw new JsonError("Passwords don't match!", 400)
            }

            await getConnection().transaction(async (manager) => {
                const user = new User()
                user.email = req.body.email
                user.fullName = req.body.fullName
                user.createdAt = new Date()
                user.updatedAt = new Date()
                user.lastLogin = new Date()
                await user.setPassword(req.body.password)
                await manager.getRepository(User).save(user)

                // Remove the invite now that it has been used successfully
                await manager.remove(invite)
            })

            await logInWithCredentials(req.body.email, req.body.password)
            res.redirect("/admin")
        } catch (err) {
            res.status(tryInt(err.code, 500))
            res.send(
                renderToHtmlPage(
                    <RegisterPage errorMessage={err.message} body={req.body} />
                )
            )
        }
    }
)

adminRouter.get("/datasets/:datasetId.csv", async (req, res) => {
    const datasetId = expectInt(req.params.datasetId)

    const datasetName = (
        await db.get(`SELECT name FROM datasets WHERE id=?`, [datasetId])
    ).name
    res.attachment(filenamify(datasetName) + ".csv")

    return Dataset.writeCSV(datasetId, res)
})

adminRouter.get("/datasets/:datasetId/downloadZip", async (req, res) => {
    const datasetId = expectInt(req.params.datasetId)

    res.attachment("additional-material.zip")

    const file = await db.get(
        `SELECT filename, file FROM dataset_files WHERE datasetId=?`,
        [datasetId]
    )
    res.send(file.file)
})

adminRouter.get("/posts/preview/:postId", async (req, res) => {
    const postId = expectInt(req.params.postId)

    res.send(await renderPreview(postId))
})

addExplorerAdminRoutes(adminRouter)

export { adminRouter }
