/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
type jsonString = string
export interface active_datasetsRow {
  'createdAt'?: Date;
  'createdByUserId': number;
  'dataEditedAt': Date;
  'dataEditedByUserId': number;
  'description': string;
  'id'?: number;
  'isArchived'?: number;
  'isPrivate'?: number;
  'metadataEditedAt': Date;
  'metadataEditedByUserId': number;
  'name': string | null;
  'namespace': string;
  'nonRedistributable'?: number;
  'shortName': string | null;
  'sourceChecksum': string | null;
  'updatedAt': Date | null;
  'updatePeriodDays': number | null;
  'version': string | null;
}
export interface analytics_pageviewsRow {
  'day': Date;
  'url': string;
  'views_14d': number;
  'views_365d': number;
  'views_7d': number;
}
export interface chart_dimensionsRow {
  'chartId': number;
  'createdAt'?: Date;
  'id'?: number;
  'order': number;
  'property': string;
  'updatedAt': Date | null;
  'variableId': number;
}
export interface chart_revisionsRow {
  'chartId': number | null;
  'config': jsonString | null;
  'createdAt'?: Date;
  'id'?: string;
  'updatedAt': Date | null;
  'userId': number | null;
}
export interface chart_slug_redirectsRow {
  'chart_id': number;
  'createdAt'?: Date;
  'id'?: number;
  'slug': string;
  'updatedAt': Date | null;
}
export interface chart_tagsRow {
  'chartId': number;
  'createdAt'?: Date;
  'isApproved'?: number;
  'keyChartLevel'?: number;
  'tagId': number;
  'updatedAt': Date | null;
}
export interface chartsRow {
  'config': jsonString;
  'createdAt'?: Date;
  'id'?: number;
  'is_indexable'?: number;
  'isExplorable'?: number;
  'lastEditedAt': Date;
  'lastEditedByUserId': number;
  'publishedAt': Date | null;
  'publishedByUserId': number | null;
  'slug': string | null;
  'type': string | null;
  'updatedAt': Date | null;
}
export interface country_latest_dataRow {
  'country_code': string | null;
  'value': string | null;
  'variable_id': number | null;
  'year': number | null;
}
export interface country_name_tool_continentRow {
  'continent_code': string;
  'continent_name': string;
  'id'?: number;
}
export interface country_name_tool_countrydataRow {
  'continent': number | null;
  'cow_code': number | null;
  'cow_letter': string | null;
  'id'?: number;
  'imf_code': number | null;
  'iso_alpha2': string | null;
  'iso_alpha3': string | null;
  'kansas_code': string | null;
  'marc_code': string | null;
  'ncd_code': string | null;
  'owid_name': string;
  'penn_code': string | null;
  'unctad_code': string | null;
}
export interface country_name_tool_countrynameRow {
  'country_name': string;
  'id'?: number;
  'owid_country': number;
}
export interface dataset_filesRow {
  'createdAt'?: Date;
  'datasetId': number;
  'file': any;
  'filename': string;
  'updatedAt': Date | null;
}
export interface dataset_tagsRow {
  'createdAt'?: Date;
  'datasetId': number;
  'tagId': number;
  'updatedAt': Date | null;
}
export interface datasetsRow {
  'createdAt'?: Date;
  'createdByUserId': number;
  'dataEditedAt': Date;
  'dataEditedByUserId': number;
  'description': string;
  'id'?: number;
  'isArchived'?: number;
  'isPrivate'?: number;
  'metadataEditedAt': Date;
  'metadataEditedByUserId': number;
  'name': string | null;
  'namespace': string;
  'nonRedistributable'?: number;
  'shortName': string | null;
  'sourceChecksum': string | null;
  'updatedAt': Date | null;
  'updatePeriodDays': number | null;
  'version': string | null;
}
export interface entitiesRow {
  'code': string | null;
  'createdAt'?: Date;
  'displayName': string;
  'id'?: number;
  'name': string;
  'updatedAt': Date | null;
  'validated': number;
}
export interface explorer_chartsRow {
  'chartId': number;
  'explorerSlug': string;
  'id'?: number;
}
export interface explorer_variablesRow {
  'explorerSlug': string;
  'id'?: number;
  'variableId': number;
}
export interface explorersRow {
  'config': jsonString;
  'createdAt'?: Date | null;
  'isPublished': number;
  'slug': string;
  'updatedAt'?: Date | null;
}
export interface imagesRow {
  'defaultAlt': string;
  'filename': string;
  'googleId': string;
  'id'?: number;
  'originalWidth': number | null;
  'updatedAt': string | null;
}
export interface importer_additionalcountryinfoRow {
  'country_code': string;
  'country_latest_census': string | null;
  'country_latest_survey': string | null;
  'country_name': string;
  'country_recent_income_source': string | null;
  'country_special_notes': string | null;
  'country_wb_income_group': string | null;
  'country_wb_region': string | null;
  'dataset': string;
  'id'?: number;
}
export interface importer_importhistoryRow {
  'id'?: number;
  'import_notes': string;
  'import_state': string;
  'import_time': Date;
  'import_type': string;
}
export interface migrationsRow {
  'id'?: number;
  'name': string;
  'timestamp': string;
}
export interface namespacesRow {
  'createdAt'?: Date;
  'description': string | null;
  'id'?: number;
  'isArchived'?: number;
  'name': string;
  'updatedAt': Date | null;
}
export interface originsRow {
  'attribution': string | null;
  'attributionShort': string | null;
  'citationFull': string | null;
  'dateAccessed': Date | null;
  'datePublished': string | null;
  'description': string | null;
  'descriptionSnapshot': string | null;
  'id'?: number;
  'license': jsonString | null;
  'producer': string | null;
  'title': string | null;
  'titleSnapshot': string | null;
  'urlDownload': string | null;
  'urlMain': string | null;
  'versionProducer': string | null;
}
export interface origins_variablesRow {
  'displayOrder'?: number;
  'originId': number;
  'variableId': number;
}
export interface post_tagsRow {
  'createdAt'?: Date;
  'post_id': number;
  'tag_id': number;
  'updatedAt': Date | null;
}
export interface postsRow {
  'archieml': jsonString | null;
  'archieml_update_statistics': jsonString | null;

  /** json array of objects with field author in the form "firstname lastname" and field order */
  'authors': jsonString | null;
  'content': string;
  'created_at_in_wordpress': Date | null;
  'excerpt': string | null;
  'featured_image'?: string;
  'formattingOptions': jsonString | null;
  'gdocSuccessorId': string | null;
  'id'?: number;
  'markdown': string | null;
  'published_at': Date | null;
  'slug': string;
  'status': string;
  'title': string;
  'type': string;
  'updated_at': Date | null;
  'updated_at_in_wordpress': Date | null;
}
export interface posts_gdocsRow {
  'breadcrumbs': jsonString | null;
  'content': jsonString;
  'createdAt': Date;
  'id': string;
  'markdown': string | null;
  'publicationContext'?: any;
  'published': number;
  'publishedAt': Date | null;
  'revisionId': string | null;
  'slug': string;
  'updatedAt': Date | null;
}
export interface posts_gdocs_linksRow {
  'componentType': string;
  'hash': string;
  'id'?: number;
  'linkType': any | null;
  'queryString': string;
  'sourceId': string | null;
  'target': string;
  'text': string;
}
export interface posts_gdocs_variables_faqsRow {
  'displayOrder'?: number;
  'fragmentId': string;
  'gdocId': string;
  'variableId': number;
}
export interface posts_gdocs_x_imagesRow {
  'gdocId': string;
  'id'?: number;
  'imageId': number;
}
export interface posts_gdocs_x_tagsRow {
  'gdocId': string;
  'tagId': number;
}
export interface posts_linksRow {
  'componentType': string;
  'hash': string;
  'id'?: number;
  'linkType': any | null;
  'queryString': string;
  'sourceId': number;
  'target': string;
  'text': string;
}
export interface posts_with_gdoc_publish_statusRow {
  'archieml': jsonString | null;
  'archieml_update_statistics': jsonString | null;

  /** json array of objects with field author in the form "firstname lastname" and field order */
  'authors': jsonString | null;
  'content': string;
  'created_at_in_wordpress': Date | null;
  'excerpt': string | null;
  'gdocSuccessorId': string | null;
  'id'?: number;
  'isGdocPublished'?: number;
  'published_at': Date | null;
  'slug': string;
  'status': string;
  'title': string;
  'type': string;
  'updated_at': Date | null;
  'updated_at_in_wordpress': Date | null;
}
export interface sessionsRow {
  'expire_date': Date;
  'session_data': string;
  'session_key': string;
}
export interface sourcesRow {
  'createdAt'?: Date;
  'datasetId': number | null;
  'description': jsonString;
  'id'?: number;
  'name': string | null;
  'updatedAt': Date | null;
}
export interface suggested_chart_revisionsRow {
  'changesInDataSummary': string | null;
  'chartId': number;
  'createdAt'?: Date;
  'createdBy': number;
  'decisionReason': string | null;
  'experimental': jsonString | null;
  'id'?: string;
  'isPendingOrFlagged': number | null;
  'originalConfig': jsonString;
  'originalVersion': number;
  'status': string;
  'suggestedConfig': jsonString;
  'suggestedReason': string | null;
  'suggestedVersion': number;
  'updatedAt': Date | null;
  'updatedBy': number | null;
}
export interface tagsRow {
  'createdAt'?: Date;
  'id'?: number;
  'isBulkImport'?: number;
  'name': string;
  'parentId': number | null;
  'slug': string | null;
  'specialType': string | null;
  'updatedAt': Date | null;
}
export interface tags_variables_topic_tagsRow {
  'displayOrder'?: number;
  'tagId': number;
  'variableId': number;
}
export interface usersRow {
  'createdAt'?: Date;
  'email': string;
  'fullName': string;
  'id'?: number;
  'isActive'?: number;
  'isSuperuser'?: number;
  'lastLogin': Date | null;
  'lastSeen': Date | null;
  'password': string | null;
  'updatedAt': Date | null;
}
export interface variablesRow {
  'attribution': string | null;
  'attributionShort': string | null;
  'catalogPath': string | null;
  'code': string | null;
  'columnOrder'?: number;
  'coverage': string;
  'createdAt'?: Date;
  'datasetId': number;
  'description': string | null;
  'descriptionFromProducer': string | null;
  'descriptionKey': jsonString | null;
  'descriptionProcessing': string | null;
  'descriptionShort': string | null;
  'dimensions': jsonString | null;
  'display': jsonString;
  'grapherConfigAdmin': jsonString | null;
  'grapherConfigETL': jsonString | null;
  'id'?: number;
  'license': jsonString | null;
  'licenses': jsonString | null;
  'name': string | null;
  'originalMetadata': jsonString | null;
  'processingLevel': string | null;
  'processingLog': jsonString | null;
  'schemaVersion'?: number;
  'shortName': string | null;
  'shortUnit': string | null;
  'sourceId': number | null;
  'timespan': string;
  'titlePublic': string | null;
  'titleVariant': string | null;
  'unit': string;
  'updatedAt': Date | null;
}
