# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=255)),
                ('import_time', models.DateTimeField()),
                ('import_notes', models.TextField()),
                ('import_state', models.TextField()),
            ],
        ),
    ]
