# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=255, unique=True)),
                ('country_name', models.CharField(max_length=255, unique=True)),
                ('country_wb_region', models.CharField(max_length=255, null=True)),
                ('country_wb_income_group', models.CharField(max_length=255, null=True)),
                ('country_special_notes', models.TextField(null=True)),
                ('country_latest_census', models.CharField(max_length=255, null=True)),
                ('country_latest_survey', models.CharField(max_length=255, null=True)),
                ('country_recent_income_source', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
