# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_additionalcountryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcountryinfo',
            name='dataset',
            field=models.CharField(default='wdi', max_length=255),
        ),
        migrations.AlterField(
            model_name='additionalcountryinfo',
            name='country_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='additionalcountryinfo',
            name='country_name',
            field=models.CharField(max_length=255),
        ),
    ]
