export {
    type RegionType,
    type Region,
    type Country,
    type IncomeGroup,
    type OwidIncomeGroupCode,
    type OwidIncomeGroupName,
    type Continent,
    type Aggregate,
    type BaseRegion,
    type RegionDataProvider,
    type AggregateWithDefinedBy,
} from "./regionsTypes.js"

export { regions } from "./regions.js"

export {
    checkIsCountry,
    checkIsAggregate,
    checkIsOwidContinent,
    checkIsIncomeGroup,
    checkHasMembers,
    checkIsOwidIncomeGroupCode,
    countries,
    mappableCountries,
    getContinents,
    getIncomeGroups,
    getAggregates,
    listedRegionsNames,
    getRegionDataProviders,
    getAggregatesByProvider,
    countriesByName,
    incomeGroupsByCode,
    getRegionByName,
    getRegionBySlug,
    getRegionByShortName,
    getRegionByNameOrVariantName,
    getCountryByName,
    getCountryBySlug,
    getParentRegions,
    getSiblingRegions,
    getContinentForCountry,
    getCountryNamesForRegion,
    getRegionAlternativeNames,
    articulateEntity,
} from "./regionsUtils.js"
