import * as _ from "lodash-es"
import {
    EntityName,
    GrapherQueryParams,
    GrapherTabName,
    GRAPHER_TAB_NAMES,
    GRAPHER_TAB_QUERY_PARAMS,
    MapRegionName,
    Time,
} from "@ourworldindata/types"
import {
    getCountryNamesForRegion,
    getRegionByName,
} from "@ourworldindata/utils"
import { generateSelectedEntityNamesParam } from "../core/EntityUrlBuilder.js"
import { isWorldEntityName } from "../core/GrapherConstants.js"

/**
 * Prototype backend for the "AI assistant (BETA)" panel on data pages.
 *
 * The assistant never returns freeform prose. Every response is either:
 * - "apply": a single concrete chart view (as Grapher query params) that is
 *   applied immediately, plus a templated confirmation string, or
 * - "options": a list of concrete chart views the user can click.
 *
 * All descriptions are generated by the deterministic `describeView` template
 * below — never authored freely by the backend. A future LLM-based backend
 * should implement `AssistantBackend` and produce `AssistantView` objects that
 * are run through the same template, so it also can't emit prose.
 */

/** Chart context handed to the backend alongside the user's query */
export interface AssistantChartContext {
    availableEntityNames: EntityName[]
    availableTabs: GrapherTabName[]
    activeTab: GrapherTabName
    /** All times with data, sorted ascending */
    availableTimes: Time[]
    selectedEntityNames: EntityName[]
    /**
     * Latest data value per country entity (aggregates excluded), used to
     * answer "top/bottom N" queries
     */
    latestValueByEntityName: Map<EntityName, number>
}

/** A structured description of a chart view, the assistant's only "language" */
export interface AssistantView {
    tab?: GrapherTabName
    entityNames?: EntityName[]
    /**
     * Optional templated summary shown instead of listing all entity names,
     * e.g. "All countries in Africa (54)". Must be produced by a deterministic
     * template, never authored freely.
     */
    entitySummary?: string
    startTime?: Time
    endTime?: Time
    /** Map region to zoom to (map tab only) */
    mapRegion?: MapRegionName
}

export interface AssistantViewOption {
    params: GrapherQueryParams
    description: string
}

export type AssistantResponse =
    | { kind: "apply"; params: GrapherQueryParams; description: string }
    | { kind: "options"; options: AssistantViewOption[]; note?: string }

export interface AssistantBackend {
    respond(
        query: string,
        context: AssistantChartContext
    ): Promise<AssistantResponse>
}

export const ASSISTANT_UNMATCHED_NOTE =
    "Couldn't match that to a view of this chart. Try one of these:"

// -----------------------------------------------------------------------------
// Templating: views -> query params + description
// -----------------------------------------------------------------------------

const TAB_LABELS: Record<GrapherTabName, string> = {
    [GRAPHER_TAB_NAMES.Table]: "Data table",
    [GRAPHER_TAB_NAMES.WorldMap]: "Map",
    [GRAPHER_TAB_NAMES.LineChart]: "Line chart",
    [GRAPHER_TAB_NAMES.ScatterPlot]: "Scatter plot",
    [GRAPHER_TAB_NAMES.StackedArea]: "Stacked area chart",
    [GRAPHER_TAB_NAMES.DiscreteBar]: "Bar chart",
    [GRAPHER_TAB_NAMES.StackedDiscreteBar]: "Stacked bar chart",
    [GRAPHER_TAB_NAMES.SlopeChart]: "Slope chart",
    [GRAPHER_TAB_NAMES.StackedBar]: "Stacked bar chart",
    [GRAPHER_TAB_NAMES.Marimekko]: "Marimekko chart",
    [GRAPHER_TAB_NAMES.Dumbbell]: "Dumbbell chart",
}

const TAB_QUERY_PARAM_VALUES: Record<GrapherTabName, string> = {
    [GRAPHER_TAB_NAMES.Table]: GRAPHER_TAB_QUERY_PARAMS.table,
    [GRAPHER_TAB_NAMES.WorldMap]: GRAPHER_TAB_QUERY_PARAMS.map,
    [GRAPHER_TAB_NAMES.LineChart]: GRAPHER_TAB_QUERY_PARAMS.line,
    [GRAPHER_TAB_NAMES.ScatterPlot]: GRAPHER_TAB_QUERY_PARAMS.scatter,
    [GRAPHER_TAB_NAMES.StackedArea]: GRAPHER_TAB_QUERY_PARAMS["stacked-area"],
    [GRAPHER_TAB_NAMES.DiscreteBar]: GRAPHER_TAB_QUERY_PARAMS["discrete-bar"],
    [GRAPHER_TAB_NAMES.StackedDiscreteBar]:
        GRAPHER_TAB_QUERY_PARAMS["stacked-discrete-bar"],
    [GRAPHER_TAB_NAMES.SlopeChart]: GRAPHER_TAB_QUERY_PARAMS.slope,
    [GRAPHER_TAB_NAMES.StackedBar]: GRAPHER_TAB_QUERY_PARAMS["stacked-bar"],
    [GRAPHER_TAB_NAMES.Marimekko]: GRAPHER_TAB_QUERY_PARAMS.marimekko,
    [GRAPHER_TAB_NAMES.Dumbbell]: GRAPHER_TAB_QUERY_PARAMS.dumbbell,
}

const MAP_REGION_LABELS: Record<MapRegionName, string> = {
    [MapRegionName.World]: "World",
    [MapRegionName.Africa]: "Africa",
    [MapRegionName.NorthAmerica]: "North America",
    [MapRegionName.SouthAmerica]: "South America",
    [MapRegionName.Asia]: "Asia",
    [MapRegionName.Europe]: "Europe",
    [MapRegionName.Oceania]: "Oceania",
}

const MAX_LISTED_ENTITIES = 3

/**
 * Deterministic template that turns a view into a short description,
 * e.g. "Map · 2024" or "Line chart · Nigeria, Ethiopia · 1990–2020".
 * This is the only way the assistant produces text about a view.
 */
export function describeView(
    view: AssistantView,
    context: AssistantChartContext
): string {
    const parts: string[] = []

    const tab = view.tab ?? context.activeTab
    parts.push(TAB_LABELS[tab] ?? tab)

    if (view.mapRegion && view.mapRegion !== MapRegionName.World)
        parts.push(MAP_REGION_LABELS[view.mapRegion])

    if (view.entitySummary) {
        parts.push(view.entitySummary)
    } else if (view.entityNames && view.entityNames.length > 0) {
        const listed = view.entityNames.slice(0, MAX_LISTED_ENTITIES)
        const more = view.entityNames.length - listed.length
        parts.push(
            more > 0 ? `${listed.join(", ")} + ${more} more` : listed.join(", ")
        )
    }

    const time = describeViewTime(view)
    if (time) parts.push(time)

    return parts.join(" · ")
}

function describeViewTime(view: AssistantView): string | undefined {
    const { startTime, endTime } = view
    if (startTime !== undefined && endTime !== undefined)
        return startTime === endTime ? `${endTime}` : `${startTime}–${endTime}`
    if (startTime !== undefined) return `Since ${startTime}`
    if (endTime !== undefined) return `Until ${endTime}`
    return undefined
}

/** Turns a view into Grapher query params that can be applied to the chart */
export function viewToQueryParams(
    view: AssistantView,
    context: AssistantChartContext
): GrapherQueryParams {
    const params: GrapherQueryParams = {}

    const effectiveTab = view.tab ?? context.activeTab
    if (view.tab) params.tab = TAB_QUERY_PARAM_VALUES[view.tab]

    if (view.entityNames && view.entityNames.length > 0) {
        // Selecting the World entity on the map is a no-op, skip it
        const isWorldOnMap =
            effectiveTab === GRAPHER_TAB_NAMES.WorldMap &&
            view.entityNames.every(isWorldEntityName)
        if (!isWorldOnMap)
            params.country = generateSelectedEntityNamesParam(view.entityNames)
    }

    if (effectiveTab === GRAPHER_TAB_NAMES.WorldMap) {
        // Make map views deterministic: always set the map zoom, and either
        // highlight the requested entities or clear a stale map selection
        params.region = view.mapRegion ?? MapRegionName.World
        params.mapSelect = params.country ?? ""
    }

    const { startTime, endTime } = view
    if (startTime !== undefined && endTime !== undefined)
        params.time =
            startTime === endTime ? `${endTime}` : `${startTime}..${endTime}`
    else if (startTime !== undefined) params.time = `${startTime}..latest`
    else if (endTime !== undefined) params.time = `earliest..${endTime}`

    return params
}

export function makeViewOption(
    view: AssistantView,
    context: AssistantChartContext
): AssistantViewOption {
    return {
        params: viewToQueryParams(view, context),
        description: describeView(view, context),
    }
}

// -----------------------------------------------------------------------------
// Default options, shown before the first query and as a fallback
// -----------------------------------------------------------------------------

const CONTINENT_ENTITY_NAMES = [
    "Africa",
    "Asia",
    "Europe",
    "North America",
    "South America",
    "Oceania",
]

export function buildDefaultOptions(
    context: AssistantChartContext
): AssistantViewOption[] {
    const availableTabs = new Set(context.availableTabs)
    const availableEntities = new Set(context.availableEntityNames)
    const latestTime = _.last(context.availableTimes)
    const views: AssistantView[] = []

    if (availableTabs.has(GRAPHER_TAB_NAMES.WorldMap))
        views.push({
            tab: GRAPHER_TAB_NAMES.WorldMap,
            startTime: latestTime,
            endTime: latestTime,
        })

    const worldEntity = context.availableEntityNames.find(isWorldEntityName)
    if (worldEntity && availableTabs.has(GRAPHER_TAB_NAMES.LineChart))
        views.push({
            tab: GRAPHER_TAB_NAMES.LineChart,
            entityNames: [worldEntity],
        })

    const availableContinents = CONTINENT_ENTITY_NAMES.filter((name) =>
        availableEntities.has(name)
    )
    if (
        availableContinents.length >= 2 &&
        availableTabs.has(GRAPHER_TAB_NAMES.LineChart)
    )
        views.push({
            tab: GRAPHER_TAB_NAMES.LineChart,
            entityNames: availableContinents.slice(0, 4),
        })

    if (
        context.selectedEntityNames.length >= 2 &&
        availableTabs.has(GRAPHER_TAB_NAMES.LineChart)
    )
        views.push({
            tab: GRAPHER_TAB_NAMES.LineChart,
            entityNames: context.selectedEntityNames,
        })

    if (availableTabs.has(GRAPHER_TAB_NAMES.Table))
        views.push({ tab: GRAPHER_TAB_NAMES.Table })

    const options = views.map((view) => makeViewOption(view, context))
    return _.uniqBy(options, (option) => option.description).slice(0, 5)
}

// -----------------------------------------------------------------------------
// Mock matcher: deterministic, generalizing keyword/entity/time matching
// -----------------------------------------------------------------------------

const MOCK_RESPONSE_DELAY_MS = 600

export class MockAssistantBackend implements AssistantBackend {
    async respond(
        query: string,
        context: AssistantChartContext
    ): Promise<AssistantResponse> {
        // Artificial delay so the UI's pending state is visible
        await new Promise((resolve) =>
            setTimeout(resolve, MOCK_RESPONSE_DELAY_MS)
        )
        return matchQueryToResponse(query, context)
    }
}

/** Exported for testing: the deterministic matching logic without the delay */
export function matchQueryToResponse(
    query: string,
    context: AssistantChartContext
): AssistantResponse {
    const trimmedQuery = query.trim()
    if (!trimmedQuery)
        return { kind: "options", options: buildDefaultOptions(context) }

    const lowerQuery = ` ${trimmedQuery.toLowerCase()} `

    const tab = detectTabIntent(lowerQuery, context)
    const timeRange = detectTimeRange(lowerQuery, context)
    const entityNames = detectEntities(trimmedQuery, context)
    const topBottom = detectTopBottomN(lowerQuery)

    // "top/bottom N" queries are inherently ambiguous -> always offer options
    if (topBottom) {
        const response = buildTopBottomOptions(
            topBottom,
            tab,
            timeRange,
            context
        )
        if (response) return response
    }

    // "compare X and Y" implies a chart over time
    const isCompareQuery = /\bcompare\b|\bvs\.?\s|\bversus\b/.test(lowerQuery)
    const availableTabs = new Set(context.availableTabs)
    let effectiveTab = tab
    if (
        !effectiveTab &&
        isCompareQuery &&
        entityNames.length >= 2 &&
        availableTabs.has(GRAPHER_TAB_NAMES.LineChart)
    )
        effectiveTab = GRAPHER_TAB_NAMES.LineChart

    // A single matched region aggregate is ambiguous: the aggregate itself,
    // or the countries within it?
    if (entityNames.length === 1) {
        const regionResponse = handleRegionMatch(
            entityNames[0],
            effectiveTab,
            timeRange,
            context
        )
        if (regionResponse) return regionResponse
    }

    const hasSignal =
        effectiveTab !== undefined ||
        entityNames.length > 0 ||
        timeRange !== undefined

    if (!hasSignal)
        return {
            kind: "options",
            note: ASSISTANT_UNMATCHED_NOTE,
            options: buildDefaultOptions(context),
        }

    // Exactly one coherent view -> apply it immediately
    const view: AssistantView = {
        tab: effectiveTab,
        entityNames: entityNames.length > 0 ? entityNames : undefined,
        ...timeRange,
    }
    return {
        kind: "apply",
        params: viewToQueryParams(view, context),
        description: describeView(view, context),
    }
}

// --- tab intent ---------------------------------------------------------------

function detectTabIntent(
    lowerQuery: string,
    context: AssistantChartContext
): GrapherTabName | undefined {
    const availableTabs = new Set(context.availableTabs)
    const matchers: Array<[RegExp, GrapherTabName]> = [
        [/\bmap\b|\bglobe\b|\bchoropleth\b/, GRAPHER_TAB_NAMES.WorldMap],
        [/\btable\b|\bdata table\b/, GRAPHER_TAB_NAMES.Table],
        [/\bslope\b/, GRAPHER_TAB_NAMES.SlopeChart],
        [/\bscatter\b/, GRAPHER_TAB_NAMES.ScatterPlot],
        [/\bstacked area\b|\barea chart\b/, GRAPHER_TAB_NAMES.StackedArea],
        [/\bbar chart\b|\bbars\b/, GRAPHER_TAB_NAMES.DiscreteBar],
        [
            /\bline\b|\bover time\b|\btrend\b|\bevolution\b|\bhistory\b|\bthrough time\b|\bdevelopment\b/,
            GRAPHER_TAB_NAMES.LineChart,
        ],
    ]
    for (const [pattern, tabName] of matchers) {
        if (pattern.test(lowerQuery) && availableTabs.has(tabName))
            return tabName
    }
    return undefined
}

// --- time ---------------------------------------------------------------------

interface AssistantTimeRange {
    startTime?: Time
    endTime?: Time
}

function detectTimeRange(
    lowerQuery: string,
    context: AssistantChartContext
): AssistantTimeRange | undefined {
    const times = context.availableTimes
    if (times.length === 0) return undefined
    const earliest = times[0]
    const latest = times[times.length - 1]

    const clamp = (year: number): Time =>
        _.minBy(times, (time) => Math.abs(time - year)) ?? year

    const years = [...lowerQuery.matchAll(/\b(1[5-9]\d\d|2\d{3})\b/g)]
        .map((match) => Number(match[1]))
        .map(clamp)

    if (years.length >= 2) {
        return { startTime: Math.min(...years), endTime: Math.max(...years) }
    }

    if (years.length === 1) {
        const year = years[0]
        if (/\b(since|from|after|starting)\s+(the year )?\d/.test(lowerQuery))
            return { startTime: year }
        if (/\b(until|up to|before)\s+(the year )?\d/.test(lowerQuery))
            return { endTime: year }
        return { startTime: year, endTime: year }
    }

    if (/\b(latest|most recent|newest|current|today|now)\b/.test(lowerQuery))
        return { startTime: latest, endTime: latest }

    if (
        /\ball years\b|\bfull (time )?range\b|\bwhole period\b/.test(lowerQuery)
    )
        return { startTime: earliest, endTime: latest }

    return undefined
}

// --- entities -------------------------------------------------------------------

function isWordChar(char: string | undefined): boolean {
    return char !== undefined && /[a-z0-9]/i.test(char)
}

/** Phrases that look like entities but are chart-type keywords */
const ENTITY_STOP_PHRASES = [/world map/gi, /world bank/gi]

function detectEntities(
    query: string,
    context: AssistantChartContext
): EntityName[] {
    interface Candidate {
        pattern: string
        entityName: EntityName
        caseSensitive: boolean
    }

    const candidates: Candidate[] = []
    const availableEntities = new Set(context.availableEntityNames)
    for (const entityName of context.availableEntityNames) {
        const region = getRegionByName(entityName)
        const variantNames =
            region && "variantNames" in region
                ? (region.variantNames ?? [])
                : []
        const patterns = new Set<string>([entityName, ...variantNames])
        // Entities like "Sub-Saharan Africa (WB)" should also match queries
        // without the parenthetical suffix, unless the plain name is itself
        // an available entity
        const plainName = entityName.replace(/\s*\([^)]*\)\s*$/, "")
        if (plainName !== entityName && !availableEntities.has(plainName))
            patterns.add(plainName)
        for (const pattern of patterns) {
            candidates.push({
                pattern,
                entityName,
                // Short codes like "US", "UK", "UAE" must match exact case so
                // that e.g. the word "us" doesn't select the United States
                caseSensitive: pattern.length <= 3,
            })
        }
    }
    // Prefer longer matches ("South Sudan" before "Sudan")
    candidates.sort((a, b) => b.pattern.length - a.pattern.length)

    let masked = ` ${query} `
    for (const stopPhrase of ENTITY_STOP_PHRASES)
        masked = masked.replace(stopPhrase, (match) => " ".repeat(match.length))
    let maskedLower = masked.toLowerCase()

    const matchedIndices: Array<{ index: number; entityName: EntityName }> = []
    const matchedEntities = new Set<EntityName>()

    for (const candidate of candidates) {
        if (matchedEntities.has(candidate.entityName)) continue
        const haystack = candidate.caseSensitive ? masked : maskedLower
        const needle = candidate.caseSensitive
            ? candidate.pattern
            : candidate.pattern.toLowerCase()

        let index = haystack.indexOf(needle)
        while (index !== -1) {
            const charBefore = haystack[index - 1]
            const charAfter = haystack[index + needle.length]
            if (!isWordChar(charBefore) && !isWordChar(charAfter)) {
                matchedEntities.add(candidate.entityName)
                matchedIndices.push({ index, entityName: candidate.entityName })
                const mask = " ".repeat(needle.length)
                masked =
                    masked.slice(0, index) +
                    mask +
                    masked.slice(index + needle.length)
                maskedLower =
                    maskedLower.slice(0, index) +
                    mask +
                    maskedLower.slice(index + needle.length)
                break
            }
            index = haystack.indexOf(needle, index + 1)
        }
    }

    // Return entities in the order they appear in the query
    return _.sortBy(matchedIndices, (match) => match.index).map(
        (match) => match.entityName
    )
}

// --- region aggregates ----------------------------------------------------------

const MAP_REGION_BY_ENTITY_NAME: Record<string, MapRegionName> = {
    Africa: MapRegionName.Africa,
    Asia: MapRegionName.Asia,
    Europe: MapRegionName.Europe,
    "North America": MapRegionName.NorthAmerica,
    "South America": MapRegionName.SouthAmerica,
    Oceania: MapRegionName.Oceania,
}

/**
 * Handles a query that matched a single region aggregate (e.g. "Africa").
 * On the map tab a continent can be applied directly as a map zoom; otherwise
 * it's ambiguous whether the user wants the aggregate or its member countries.
 */
function handleRegionMatch(
    entityName: EntityName,
    tab: GrapherTabName | undefined,
    timeRange: AssistantTimeRange | undefined,
    context: AssistantChartContext
): AssistantResponse | undefined {
    if (isWorldEntityName(entityName)) return undefined

    const region = getRegionByName(entityName)
    // Countries don't have a `members` list; only region aggregates do
    if (!region || !("members" in region)) return undefined

    const availableEntities = new Set(context.availableEntityNames)
    const memberCountries = getCountryNamesForRegion(region).filter((name) =>
        availableEntities.has(name)
    )

    const mapRegion = MAP_REGION_BY_ENTITY_NAME[entityName]

    // "Map of Africa" is unambiguous: zoom the map to the region
    if (tab === GRAPHER_TAB_NAMES.WorldMap && mapRegion) {
        const view: AssistantView = { tab, mapRegion, ...timeRange }
        return {
            kind: "apply",
            params: viewToQueryParams(view, context),
            description: describeView(view, context),
        }
    }

    if (memberCountries.length < 3) return undefined

    const availableTabs = new Set(context.availableTabs)

    // Entity-based options need a chart tab: selecting entities "on the map"
    // isn't a meaningful view, so fall back to a line chart in that case
    let chartTab = tab ?? context.activeTab
    if (
        chartTab === GRAPHER_TAB_NAMES.WorldMap &&
        availableTabs.has(GRAPHER_TAB_NAMES.LineChart)
    )
        chartTab = GRAPHER_TAB_NAMES.LineChart

    // Ambiguous: the aggregate itself vs. the countries in the region
    const views: AssistantView[] = [
        { tab: chartTab, entityNames: [entityName], ...timeRange },
        {
            tab: chartTab,
            entityNames: memberCountries,
            entitySummary: `All countries in ${entityName} (${memberCountries.length})`,
            ...timeRange,
        },
    ]
    if (mapRegion && availableTabs.has(GRAPHER_TAB_NAMES.WorldMap))
        views.push({
            tab: GRAPHER_TAB_NAMES.WorldMap,
            mapRegion,
            ...timeRange,
        })

    const options = views.map((view) => makeViewOption(view, context))
    return {
        kind: "options",
        options: _.uniqBy(options, (option) => option.description),
    }
}

// --- top/bottom N -----------------------------------------------------------------

interface TopBottomIntent {
    order: "highest" | "lowest"
    count: number
}

function detectTopBottomN(lowerQuery: string): TopBottomIntent | undefined {
    // "most recent" etc. are time phrases, not superlatives
    const cleanedQuery = lowerQuery.replace(
        /\bmost recent\b|\bleast recent\b/g,
        " "
    )

    const isHighest = /\b(top|highest|largest|biggest|greatest|most)\b/.test(
        cleanedQuery
    )
    const isLowest = /\b(bottom|lowest|smallest|least|fewest)\b/.test(
        cleanedQuery
    )
    if (!isHighest && !isLowest) return undefined

    const countMatch =
        cleanedQuery.match(/\b(?:top|bottom|highest|lowest)\s+(\d{1,2})\b/) ??
        cleanedQuery.match(/\b(\d{1,2})\s+(?:countries|nations|entities)\b/)
    const count = countMatch ? Number(countMatch[1]) : 10

    return { order: isLowest ? "lowest" : "highest", count }
}

function buildTopBottomOptions(
    intent: TopBottomIntent,
    tab: GrapherTabName | undefined,
    timeRange: AssistantTimeRange | undefined,
    context: AssistantChartContext
): AssistantResponse | undefined {
    const rankedEntries = _.orderBy(
        [...context.latestValueByEntityName.entries()],
        ([, value]) => value,
        intent.order === "highest" ? "desc" : "asc"
    )
    if (rankedEntries.length === 0) return undefined

    const entityNames = rankedEntries
        .slice(0, intent.count)
        .map(([entityName]) => entityName)
    const entitySummary = `${entityNames.length} countries with the ${intent.order} values (latest data)`

    const availableTabs = new Set(context.availableTabs)
    const views: AssistantView[] = []

    const chartTabs: GrapherTabName[] = [
        tab ?? GRAPHER_TAB_NAMES.LineChart,
        GRAPHER_TAB_NAMES.DiscreteBar,
        GRAPHER_TAB_NAMES.Table,
    ]
    for (const chartTab of _.uniq(chartTabs)) {
        if (!availableTabs.has(chartTab)) continue
        views.push({
            tab: chartTab,
            entityNames,
            entitySummary,
            ...timeRange,
        })
    }
    if (views.length === 0) return undefined

    return {
        kind: "options",
        options: views.slice(0, 3).map((view) => makeViewOption(view, context)),
    }
}
