name: Set up node and dependencies
description: Runs all the setup steps required to have the proper Node version and all dependencies installed
runs:
    using: composite
    steps:
        # Corepack must be enabled _before_ running setup-node, otherwise the caching setup will error
        - name: Enable corepack
          run: corepack enable
          shell: bash

        - name: Use Node.js (.nvmrc)
          uses: actions/setup-node@v4
          with:
              node-version-file: ".nvmrc"
              cache: "yarn"

        - name: List versions
          run: |
              echo "Versions:"
              echo "Node `node --version`"
              echo "yarn `yarn --version`"
          shell: bash

        - name: Install dependencies
          run: yarn --immutable
          shell: bash
