import { expect, it, describe } from "vitest"
import {
    rankHitsByEntityCoverage,
    validateSlug,
    validateArticlePath,
    hitPath,
    dedupeByPath,
    parseChartRef,
    isSameChartView,
    resolveTabParam,
} from "./siteTools.js"

// Shaped after the real /api/search response for "infant mortality", where the
// actual infant-mortality chart ranks third behind two child/youth mortality
// charts. Entity coverage is what lets an agent tell them apart.
const HITS = [
    {
        title: "Child mortality rate",
        slug: "child-mortality",
        type: "chart",
        availableEntities: ["Czechia", "Slovakia", "Poland"],
    },
    {
        title: "Global child mortality",
        slug: "global-child-mortality-timeseries",
        type: "chart",
        availableEntities: ["World"],
    },
    {
        title: "Infant mortality rate",
        slug: "infant-mortality",
        type: "chart",
        availableEntities: ["Czechia", "Slovakia"],
    },
]

describe(rankHitsByEntityCoverage, () => {
    it("demotes charts missing a requested entity", () => {
        const ranked = rankHitsByEntityCoverage(HITS, ["Czechia", "Slovakia"])
        expect(ranked.map((r) => r.hit.slug)).toEqual([
            "child-mortality",
            "infant-mortality",
            "global-child-mortality-timeseries",
        ])
        expect(ranked[2].missing).toEqual(["Czechia", "Slovakia"])
    })

    it("preserves OWID's search order within the covered group", () => {
        // Relevance ranking stays OWID's to own — this only separates charts
        // that can answer the question from ones that cannot.
        const ranked = rankHitsByEntityCoverage(HITS, ["Czechia"])
        expect(ranked.slice(0, 2).map((r) => r.hit.slug)).toEqual([
            "child-mortality",
            "infant-mortality",
        ])
    })

    it("leaves order untouched when no entities are requested", () => {
        const ranked = rankHitsByEntityCoverage(HITS, [])
        expect(ranked.map((r) => r.hit.slug)).toEqual(HITS.map((h) => h.slug))
        expect(ranked.every((r) => r.missing.length === 0)).toBe(true)
    })

    it("matches entity names case-insensitively", () => {
        const ranked = rankHitsByEntityCoverage(HITS, ["czechia"])
        expect(ranked[0].missing).toEqual([])
    })

    it("treats a hit with no availableEntities as missing everything", () => {
        const ranked = rankHitsByEntityCoverage(
            [{ title: "x", slug: "x", type: "chart" }],
            ["Czechia"]
        )
        expect(ranked[0].missing).toEqual(["Czechia"])
    })
})

describe(hitPath, () => {
    it("keeps the params that identify a multi-dim view", () => {
        // The whole reason v2 opened the wrong chart: these two hits share a
        // slug and differ only here.
        expect(
            hitPath({
                title: "Share of electricity generated by solar power",
                slug: "electricity-mix",
                type: "multiDimView",
                url: "https://ourworldindata.org/grapher/electricity-mix?frequency=annual&metric=share_of_generation&source=solar",
            })
        ).toBe(
            "/grapher/electricity-mix?frequency=annual&metric=share_of_generation&source=solar"
        )
    })

    it("handles explorer views", () => {
        expect(
            hitPath({
                title: "Global electricity from solar",
                slug: "ipcc-scenarios",
                type: "explorerView",
                url: "https://ourworldindata.org/explorers/ipcc-scenarios?Metric=Secondary+energy",
            })
        ).toBe("/explorers/ipcc-scenarios?Metric=Secondary+energy")
    })

    it("falls back to the slug when the API gave no url", () => {
        expect(
            hitPath({ title: "x", slug: "infant-mortality", type: "chart" })
        ).toBe("/grapher/infant-mortality")
    })
})

describe(dedupeByPath, () => {
    it("collapses the identical rows Algolia returns for one mdim view", () => {
        // Verbatim from the trace: four rows, two distinct views.
        const url = (metric: string) =>
            `https://ourworldindata.org/grapher/electricity-mix?metric=${metric}&source=solar`
        const entries = [
            {
                hit: {
                    title: "Share",
                    slug: "electricity-mix",
                    type: "multiDimView",
                    url: url("share_of_generation"),
                },
            },
            {
                hit: {
                    title: "Solar and wind",
                    slug: "electricity-mix",
                    type: "multiDimView",
                    url: url("generation"),
                },
            },
            {
                hit: {
                    title: "Share",
                    slug: "electricity-mix",
                    type: "multiDimView",
                    url: url("share_of_generation"),
                },
            },
            {
                hit: {
                    title: "Solar and wind",
                    slug: "electricity-mix",
                    type: "multiDimView",
                    url: url("generation"),
                },
            },
        ]
        expect(dedupeByPath(entries)).toHaveLength(2)
    })

    it("keeps different views of the same slug", () => {
        const entries = [
            {
                hit: {
                    title: "a",
                    slug: "electricity-mix",
                    type: "multiDimView",
                    url: "https://ourworldindata.org/grapher/electricity-mix?metric=generation",
                },
            },
            {
                hit: {
                    title: "b",
                    slug: "electricity-mix",
                    type: "multiDimView",
                    url: "https://ourworldindata.org/grapher/electricity-mix?metric=share_of_generation",
                },
            },
        ]
        expect(dedupeByPath(entries)).toHaveLength(2)
    })
})

describe(parseChartRef, () => {
    it("accepts a path from find_chart and keeps its view params", () => {
        const ref = parseChartRef(
            "/grapher/electricity-mix?metric=share_of_generation&source=solar"
        )
        expect(ref.error).toBeUndefined()
        expect(ref.path).toBe("/grapher/electricity-mix")
        expect(ref.viewParams.get("metric")).toBe("share_of_generation")
    })

    it("accepts a bare slug", () => {
        const ref = parseChartRef("infant-mortality")
        expect(ref.error).toBeUndefined()
        expect(ref.path).toBe("/grapher/infant-mortality")
        expect([...ref.viewParams]).toEqual([])
    })

    it("accepts an explorer path", () => {
        expect(parseChartRef("/explorers/ipcc-scenarios?Metric=x").path).toBe(
            "/explorers/ipcc-scenarios"
        )
    })

    it("rejects the image filename an agent produces", () => {
        expect(parseChartRef("electricity-mix.png").error).toContain(
            "is a file, not a chart slug"
        )
    })

    it("points at find_article when handed an article path", () => {
        const ref = parseChartRef("/battery-price-decline")
        expect(ref.error).toContain("not a chart page")
        expect(ref.error).toContain("find_article")
    })

    it("rejects an empty reference", () => {
        expect(parseChartRef("   ").error).toBeDefined()
    })
})

describe(isSameChartView, () => {
    const location = {
        pathname: "/grapher/electricity-mix",
        search: "?frequency=annual&metric=generation&source=solar",
    }

    it("is false for a different view of the same page", () => {
        // v2's slug-only check returned true here and refused to navigate, so
        // the user's "I wanted share, not absolute numbers" went nowhere.
        const ref = parseChartRef(
            "/grapher/electricity-mix?frequency=annual&metric=share_of_generation&source=solar"
        )
        expect(isSameChartView(ref, location)).toBe(false)
    })

    it("is true for the same page and view", () => {
        const ref = parseChartRef(
            "/grapher/electricity-mix?metric=generation&source=solar"
        )
        expect(isSameChartView(ref, location)).toBe(true)
    })

    it("is false for a different chart", () => {
        expect(
            isSameChartView(parseChartRef("infant-mortality"), location)
        ).toBe(false)
    })

    it("ignores state params the page already carries", () => {
        // A bare slug asks for no particular view, so being on that page with
        // countries selected still counts as the same view.
        expect(
            isSameChartView(parseChartRef("electricity-mix"), {
                pathname: "/grapher/electricity-mix",
                search: "?country=~CZE&tab=line",
            })
        ).toBe(true)
    })
})

describe(resolveTabParam, () => {
    it("resolves the tab a user asks for by name", () => {
        expect(resolveTabParam("line")).toBe("line")
        expect(resolveTabParam("Map")).toBe("map")
        expect(resolveTabParam("table")).toBe("table")
    })

    it("resolves the phrasings a model reaches for", () => {
        expect(resolveTabParam("line-chart")).toBe("line")
        expect(resolveTabParam("world-map")).toBe("map")
    })

    it("returns undefined for a tab that does not exist", () => {
        expect(resolveTabParam("pie")).toBeUndefined()
    })
})

describe(validateSlug, () => {
    it("accepts a real slug", () => {
        expect(validateSlug("co-emissions-per-capita")).toBeUndefined()
        expect(validateSlug("co2")).toBeUndefined()
    })

    it("rejects the filename an agent produces when it wants an image", () => {
        // v1 accepted this and navigated the tab to a PNG, unloading every tool.
        const error = validateSlug("co-emissions-per-capita.png")
        expect(error).toContain("is a file, not a chart slug")
    })

    it("rejects other non-slugs without pretending they are files", () => {
        expect(validateSlug("https://example.com/x")).toContain(
            "not a valid chart slug"
        )
        expect(validateSlug("some slug")).toContain("not a valid chart slug")
    })
})

describe(validateArticlePath, () => {
    it("accepts the nested slugs the pages index returns", () => {
        // /api/search?type=pages&q=solar lists these; open_article used to
        // refuse them as "not a valid article slug" right after find_article
        // had offered them.
        expect(
            validateArticlePath("sdgs/affordable-clean-energy")
        ).toBeUndefined()
        expect(validateArticlePath("battery-price-decline")).toBeUndefined()
    })

    it("still refuses files and foreign URLs, naming articles not charts", () => {
        expect(validateArticlePath("battery-price-decline.png")).toContain(
            "is a file, not a"
        )
        expect(validateArticlePath("https://example.com/x")).toContain(
            "not a valid article slug"
        )
        expect(validateArticlePath("")).toContain("No article")
    })
})
