import {
    type WebMcpTool,
    registerTools,
    toolResult,
    generateSelectedEntityNamesParam,
} from "@ourworldindata/grapher"
import { GRAPHER_TAB_QUERY_PARAMS } from "@ourworldindata/types"

/**
 * Site-wide WebMCP tools, registered on every page of ourworldindata.org.
 *
 * `find_chart` exists because chart selection — not chart manipulation — is the
 * step that decides whether an agent gives a useful answer. Searching
 * "infant mortality" surfaces four near-identical child-mortality charts above
 * the actual infant-mortality one, so an agent guessing at slugs will confidently
 * open the wrong chart.
 *
 * Crucially it returns a *path*, not a slug. Most OWID energy, health and
 * poverty charts are multi-dimensional: "Electricity generation from solar
 * power" and "Share of electricity generated by solar power" are both
 * /grapher/electricity-mix, distinguished only by ?metric=. A slug alone
 * collapses them into one indistinguishable row, which is exactly what an agent
 * then opens the wrong version of. `open_chart` takes the path back verbatim.
 *
 * `find_article` covers the other half of OWID: search type=charts never
 * returns prose, so an agent asked "do you have an article about X" has nothing
 * to answer from but its own memory — and will invent titles.
 *
 * `read_page` closes that loop. An agent standing on an OWID article with no
 * way to read it answers from recall, which is how you get a confident citation
 * to a paper whose title does not exist.
 */

interface SearchHit {
    title: string
    slug: string
    subtitle?: string
    variantName?: string
    type: string
    /** Absolute URL, built by the search API per hit type — for multi-dim and
     *  explorer views it carries the query params that identify the view. */
    url?: string
    availableEntities?: string[]
}

const SEARCH_RESULT_LIMIT = 5
const PAGE_TEXT_LIMIT = 20000

async function search(
    query: string,
    type: "charts" | "pages",
    signal?: AbortSignal
): Promise<SearchHit[]> {
    const url =
        `/api/search?q=${encodeURIComponent(query)}` +
        `&hitsPerPage=20${type === "pages" ? "&type=pages" : ""}`
    const response = await fetch(url, { signal })
    if (!response.ok)
        throw new Error(`Search failed with status ${response.status}`)
    const body = await response.json()
    return (body.results ?? []) as SearchHit[]
}

/**
 * The site-relative path for a hit, preserving the query params that identify
 * which view of a multi-dim chart or explorer it is. Falls back to the slug for
 * hits the API did not give a URL.
 */
export function hitPath(hit: SearchHit): string {
    if (hit.url) {
        try {
            const parsed = new URL(hit.url, "https://ourworldindata.org")
            return `${parsed.pathname}${parsed.search}`
        } catch {
            // fall through to the slug
        }
    }
    return `/grapher/${hit.slug}`
}

/**
 * Rank hits by how many of the requested entities they carry.
 *
 * Deliberately not a relevance re-ranking: search order is OWID's to own. This
 * only demotes charts that cannot answer the question at all.
 */
export function rankHitsByEntityCoverage(
    hits: SearchHit[],
    entities: string[]
): { hit: SearchHit; missing: string[] }[] {
    const scored = hits.map((hit) => {
        const available = new Set(
            (hit.availableEntities ?? []).map((name) => name.toLowerCase())
        )
        const missing = entities.filter(
            (entity) => !available.has(entity.toLowerCase())
        )
        return { hit, missing }
    })
    // Stable sort: charts covering every requested entity first, original
    // search order preserved within each group.
    return [
        ...scored.filter(({ missing }) => missing.length === 0),
        ...scored.filter(({ missing }) => missing.length > 0),
    ]
}

/**
 * Drop hits that would open the same page in the same state. Multi-dim views
 * come back from Algolia once per indexed dimension combination, so a query for
 * "share of electricity generated by solar" returned the identical title and
 * slug four times — a list an agent cannot choose from, and did not.
 */
export function dedupeByPath<T extends { hit: SearchHit }>(entries: T[]): T[] {
    const seen = new Set<string>()
    return entries.filter((entry) => {
        const path = hitPath(entry.hit)
        if (seen.has(path)) return false
        seen.add(path)
        return true
    })
}

const describeHit = (
    { hit, missing }: { hit: SearchHit; missing: string[] },
    /**
     * Only annotate coverage when it actually separates the candidates. In the
     * common case every hit carries the requested entities — "Germany" is on
     * almost every chart — and a column of identical "has all requested
     * entities" notes is noise the model has to read past.
     */
    coverageDiscriminates: boolean
): string => {
    const name = hit.variantName
        ? `${hit.title} (${hit.variantName})`
        : hit.title
    const coverage =
        coverageDiscriminates && missing.length
            ? ` — MISSING: ${missing.join(", ")}`
            : ""
    const subtitle = hit.subtitle ? ` ${hit.subtitle}` : ""
    return `chart: ${hitPath(hit)}\n   ${name}${coverage}\n  ${subtitle}`.trimEnd()
}

/** A slug, not a filename or a URL. `co-emissions-per-capita.png` is the shape
 *  an agent produces when it wants an image, and v1 happily navigated to it. */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/i

export function validateSlug(slug: string): string | undefined {
    if (SLUG_PATTERN.test(slug)) return undefined
    if (/\.(png|svg|csv|json|zip)$/i.test(slug))
        return (
            `"${slug}" is a file, not a chart slug. Drop the extension and use ` +
            `the chart's own tools for images or downloads.`
        )
    return `"${slug}" is not a valid chart slug. Use one returned by find_chart.`
}

export interface ParsedChartRef {
    path: string
    /** Params that select *which* chart/view this is, as opposed to the state
     *  (countries, years, tab) layered on top of it. */
    viewParams: URLSearchParams
    error?: string
}

/**
 * Accept either a path from find_chart (`/grapher/electricity-mix?metric=…`)
 * or a bare slug, and split it into the page and the params that identify the
 * view. Anything else is refused rather than guessed at.
 */
export function parseChartRef(chart: string): ParsedChartRef {
    const empty = { path: "", viewParams: new URLSearchParams() }
    const trimmed = chart.trim()
    if (!trimmed) return { ...empty, error: "No chart was given." }

    if (trimmed.startsWith("/") || /^https?:\/\//i.test(trimmed)) {
        let parsed: URL
        try {
            parsed = new URL(trimmed, "https://ourworldindata.org")
        } catch {
            return { ...empty, error: `"${chart}" is not a usable chart path.` }
        }
        const segments = parsed.pathname.split("/").filter(Boolean)
        const isChartPath =
            segments.length === 2 &&
            (segments[0] === "grapher" || segments[0] === "explorers")
        if (!isChartPath)
            return {
                ...empty,
                error:
                    `"${parsed.pathname}" is not a chart page. Chart paths look ` +
                    `like /grapher/<slug> or /explorers/<slug>. For an article, ` +
                    `use find_article and open_article.`,
            }
        const slugError = validateSlug(segments[1])
        if (slugError) return { ...empty, error: slugError }
        return {
            path: parsed.pathname,
            viewParams: parsed.searchParams,
        }
    }

    const slugError = validateSlug(trimmed)
    if (slugError) return { ...empty, error: slugError }
    return { path: `/grapher/${trimmed}`, viewParams: new URLSearchParams() }
}

/**
 * True when we are already looking at exactly this chart *and* view.
 *
 * v2 compared slugs alone, which on a multi-dim page meant asking for a
 * different metric of /grapher/electricity-mix was refused as redundant — the
 * agent was told to use the chart's tools for a change none of them can make.
 * Only the view-selecting params count here; countries and years are state the
 * chart's own tools should change without a page load.
 */
export function isSameChartView(
    ref: ParsedChartRef,
    location: { pathname: string; search: string }
): boolean {
    if (ref.path !== location.pathname) return false
    const current = new URLSearchParams(location.search)
    for (const [key, value] of ref.viewParams) {
        if (current.get(key) !== value) return false
    }
    return true
}

/** Validated against Grapher's own tab enum rather than a hand-written list, so
 *  a new chart type does not silently become "not a tab this chart offers". */
export function resolveTabParam(tab: string): string | undefined {
    const key = tab.trim().toLowerCase()
    const aliases: Record<string, string> = {
        "line-chart": GRAPHER_TAB_QUERY_PARAMS.line,
        "slope-chart": GRAPHER_TAB_QUERY_PARAMS.slope,
        "bar-chart": GRAPHER_TAB_QUERY_PARAMS["discrete-bar"],
        "world-map": GRAPHER_TAB_QUERY_PARAMS.map,
    }
    if (aliases[key]) return aliases[key]
    return (GRAPHER_TAB_QUERY_PARAMS as Record<string, string>)[key]
}

export function buildSiteTools(): WebMcpTool[] {
    return [
        {
            name: "find_chart",
            description:
                "Search Our World in Data's charts and return candidates as paths. " +
                "Pass the countries or regions the user asked about so charts that " +
                "lack them are flagged. Many OWID topics have several charts whose " +
                "titles differ in ways that matter, and many are different views of " +
                "the same page — so pass the whole `chart:` path back to open_chart " +
                "rather than reconstructing a URL. Present the options to the user " +
                "if more than one fits.",
            inputSchema: {
                type: "object",
                properties: {
                    query: {
                        type: "string",
                        description:
                            "Topic to search for, e.g. 'infant mortality' or 'CO2 emissions per capita'",
                    },
                    entities: {
                        type: "array",
                        items: { type: "string" },
                        description:
                            "Optional countries/regions the user cares about, e.g. ['Czechia', 'Slovakia']",
                    },
                },
                required: ["query"],
            },
            execute: async (
                {
                    query,
                    entities = [],
                }: { query: string; entities?: string[] },
                options
            ) => {
                const hits = await search(query, "charts", options?.signal)
                if (!hits.length)
                    return toolResult(`No charts found for "${query}".`)
                const ranked = dedupeByPath(
                    rankHitsByEntityCoverage(hits, entities)
                ).slice(0, SEARCH_RESULT_LIMIT)
                const coverageDiscriminates =
                    entities.length > 0 &&
                    ranked.some(({ missing }) => missing.length > 0) &&
                    ranked.some(({ missing }) => missing.length === 0)
                const lines = ranked.map((entry) =>
                    describeHit(entry, coverageDiscriminates)
                )
                return toolResult(
                    `Charts matching "${query}":\n\n${lines.join("\n\n")}\n\n` +
                        `These titles differ in ways that matter — "child mortality" is ` +
                        `not "infant mortality", and a share is not an absolute number. ` +
                        `If more than one plausibly fits, ask the user which they meant ` +
                        `rather than picking for them. Then pass the chosen "chart:" ` +
                        `path to open_chart unchanged. For articles rather than charts, ` +
                        `use find_article.`
                )
            },
        },

        {
            name: "open_chart",
            description:
                "Open an Our World in Data chart, optionally pre-configured with " +
                "specific countries, a time range and a tab. Pass the `chart:` path " +
                "from find_chart verbatim — it carries the parameters that pick which " +
                "view of a multi-dimensional chart to show. This navigates the page; " +
                "once it loads, the chart's own tools become available.",
            inputSchema: {
                type: "object",
                properties: {
                    chart: {
                        type: "string",
                        description:
                            "The `chart:` path from find_chart, e.g. " +
                            "'/grapher/electricity-mix?metric=share_of_generation&source=solar'. " +
                            "A bare slug like 'infant-mortality' also works for simple charts.",
                    },
                    entities: {
                        type: "array",
                        items: { type: "string" },
                        description:
                            "Countries/regions to show, using exact OWID names",
                    },
                    startYear: { type: "number" },
                    endYear: { type: "number" },
                    tab: {
                        type: "string",
                        enum: [
                            GRAPHER_TAB_QUERY_PARAMS.line,
                            GRAPHER_TAB_QUERY_PARAMS.map,
                            GRAPHER_TAB_QUERY_PARAMS.table,
                            GRAPHER_TAB_QUERY_PARAMS["discrete-bar"],
                            GRAPHER_TAB_QUERY_PARAMS.slope,
                        ],
                        description:
                            "Which view to open on. Use 'line' when the user asks for " +
                            "a line chart or a trend over time — charts with a map " +
                            "default to showing the map.",
                    },
                },
                required: ["chart"],
            },
            execute: async ({
                chart,
                entities,
                startYear,
                endYear,
                tab,
            }: {
                chart: string
                entities?: string[]
                startYear?: number
                endYear?: number
                tab?: string
            }) => {
                const ref = parseChartRef(chart)
                if (ref.error)
                    return toolResult(`${ref.error} Nothing was changed.`)

                // Navigation unloads the page and every tool registered on it,
                // so it is reserved for actually changing chart or view.
                // Adjusting the chart already on screen belongs to its own
                // tools.
                const changesNothing =
                    isSameChartView(ref, window.location) &&
                    !entities?.length &&
                    startYear === undefined &&
                    endYear === undefined &&
                    !tab
                if (changesNothing)
                    return toolResult(
                        `You are already looking at ${ref.path} in this exact view. ` +
                            `Do not navigate — use this page's own tools ` +
                            `(select_entities, add_entities, set_time_range, ` +
                            `set_chart_view) to change what it shows, and ` +
                            `get_chart_state to see what it is showing now.`
                    )

                const params = new URLSearchParams(ref.viewParams)
                if (tab) {
                    const resolved = resolveTabParam(tab)
                    if (!resolved)
                        return toolResult(
                            `"${tab}" is not a tab this chart offers. Nothing was changed.`
                        )
                    params.set("tab", resolved)
                }
                if (entities?.length)
                    params.set(
                        "country",
                        generateSelectedEntityNamesParam(entities)
                    )
                if (startYear !== undefined || endYear !== undefined)
                    params.set(
                        "time",
                        `${startYear ?? "earliest"}..${endYear ?? "latest"}`
                    )
                const query = params.toString()
                const url = `${ref.path}${query ? `?${query}` : ""}`
                window.location.assign(url)
                return toolResult(
                    `Opening ${url}. Once the chart loads, use get_chart_state to see ` +
                        `what it is showing and the chart's tools to adjust it. Do not ` +
                        `state any figure from it before calling get_chart_data.`
                )
            },
        },

        {
            name: "find_article",
            description:
                "Search Our World in Data's articles and written research. Use this " +
                "whenever the user asks what OWID has written about a topic, or for " +
                "an article, explainer or piece of writing — chart search does not " +
                "return prose, so answering from memory invents titles that do not " +
                "exist. Returns real titles and paths; open one with open_article.",
            inputSchema: {
                type: "object",
                properties: {
                    query: {
                        type: "string",
                        description:
                            "Topic to search for, e.g. 'solar energy' or 'battery costs'",
                    },
                },
                required: ["query"],
            },
            execute: async ({ query }: { query: string }, options) => {
                const hits = await search(query, "pages", options?.signal)
                if (!hits.length)
                    return toolResult(
                        `No Our World in Data articles found for "${query}".`
                    )
                const lines = hits
                    .slice(0, SEARCH_RESULT_LIMIT)
                    .map((hit) => `article: /${hit.slug}\n   ${hit.title}`)
                return toolResult(
                    `Our World in Data articles matching "${query}":\n\n` +
                        `${lines.join("\n\n")}\n\n` +
                        `These are the real titles. Quote them as they are, and do not ` +
                        `add articles you remember but do not see here. Use ` +
                        `open_article to open one, then read_page to read what it ` +
                        `actually says.`
                )
            },
        },

        {
            name: "open_article",
            description:
                "Open an Our World in Data article. Use an `article:` path from " +
                "find_article. This navigates the page; call read_page afterwards to " +
                "read it.",
            inputSchema: {
                type: "object",
                properties: {
                    article: {
                        type: "string",
                        description:
                            "The `article:` path from find_article, e.g. '/battery-price-decline'",
                    },
                },
                required: ["article"],
            },
            execute: async ({ article }: { article: string }) => {
                const slug = article.trim().replace(/^\/+/, "")
                const slugError = validateSlug(slug)
                if (slugError)
                    return toolResult(
                        `${slugError.replace("chart slug", "article slug")} ` +
                            `Use a path from find_article. Nothing was changed.`
                    )
                if (window.location.pathname === `/${slug}`)
                    return toolResult(
                        `You are already on /${slug}. Use read_page to read it.`
                    )
                window.location.assign(`/${slug}`)
                return toolResult(
                    `Opening /${slug}. Call read_page to read what it says before ` +
                        `answering questions about it.`
                )
            },
        },

        {
            name: "read_page",
            description:
                "Read the text of the Our World in Data page currently open — the " +
                "article body, including its footnotes and references. ALWAYS call " +
                "this before answering any question about what this page says, what " +
                "a number on it is, or where a claim on it comes from. OWID articles " +
                "are written and sourced by our researchers; the study or figure you " +
                "recall may not be the one on the page.",
            inputSchema: { type: "object", properties: {} },
            execute: async () => {
                const container =
                    document.querySelector(
                        "article.centered-article-container"
                    ) ??
                    document.querySelector("article") ??
                    document.querySelector("main") ??
                    document.body
                const text = (container as HTMLElement)?.innerText
                    ?.replace(/\n{3,}/g, "\n\n")
                    .trim()
                if (!text)
                    return toolResult(
                        `This page has no readable article text. If it is a chart ` +
                            `page, use get_chart_metadata and get_chart_data instead.`
                    )
                const title = document.title
                if (text.length <= PAGE_TEXT_LIMIT)
                    return toolResult(`${title}\n\n${text}`)
                return toolResult(
                    `${title}\n\n${text.slice(0, PAGE_TEXT_LIMIT)}\n\n` +
                        `[Truncated after ${PAGE_TEXT_LIMIT} characters of ` +
                        `${text.length}. The references and footnotes are at the end ` +
                        `of the page and may not be included above — say so rather ` +
                        `than supplying a citation from memory.]`
                )
            },
        },

        {
            name: "open_search",
            description:
                "Open Our World in Data's search results page for a topic, so the " +
                "user can browse everything we have on it. Use this only when the " +
                "user wants to browse for themselves — if they asked a question, " +
                "find_chart or find_article answers it without making them read a " +
                "results page.",
            inputSchema: {
                type: "object",
                properties: {
                    query: {
                        type: "string",
                        description: "Search terms, e.g. 'population density'",
                    },
                    resultType: {
                        type: "string",
                        enum: ["all", "data", "writing"],
                        description:
                            "'data' for charts and indicators, 'writing' for articles, " +
                            "'all' (default) for both",
                    },
                },
                required: ["query"],
            },
            execute: async ({
                query,
                resultType,
            }: {
                query: string
                resultType?: string
            }) => {
                const params = new URLSearchParams({
                    q: query,
                    resultType: resultType ?? "all",
                })
                const url = `/search?${params.toString()}`
                window.location.assign(url)
                return toolResult(
                    `Opening the search results for "${query}" at ${url}. ` +
                        `The user can browse the results themselves from here.`
                )
            },
        },
    ]
}

export async function registerSiteTools(signal?: AbortSignal): Promise<void> {
    await registerTools(buildSiteTools(), signal)
}
