import * as _ from "lodash-es"
import type { JSONSchema7 } from "json-schema"
import { format, type FormatConfig } from "oxfmt"
import oxfmtConfig from "../../.oxfmtrc.json"
import { type SchemaDefinitions, resolveRef } from "./grapherSchemaSource.js"

interface SchemaRevisionDecision {
    revision: number
    isChanged: boolean
}

/** Every `default` in the schema as one nested object */
export function generateDefaultConfig(
    schema: JSONSchema7,
    defs: SchemaDefinitions
): Record<string, unknown> {
    const defaultObject: Record<string, unknown> = {}
    if (schema.type !== "object") return defaultObject

    for (const [key, rawProperty] of Object.entries(schema.properties ?? {})) {
        const property = resolveRef(rawProperty, defs)
        if (property.type === "object") {
            const defaults = generateDefaultConfig(property, defs)
            if (Object.keys(defaults).length > 0) defaultObject[key] = defaults
        } else if (
            property.default !== undefined &&
            property.default !== null
        ) {
            defaultObject[key] = property.default
        }
    }
    return defaultObject
}

export async function renderDefaultConfigFile(
    version: string,
    defaultConfig: Record<string, unknown>
): Promise<string> {
    const outdatedSchemaVersions = _.range(1, Number(version)).map(
        (outdatedVersion) => String(outdatedVersion).padStart(3, "0")
    )

    const source = `// THIS IS A GENERATED FILE, DO NOT EDIT DIRECTLY

// GENERATED BY devTools/schema/buildGrapherSchema.ts

import { GrapherInterface } from "@ourworldindata/types"

export const latestSchemaVersion = "${version}" as const
export const outdatedSchemaVersions = ${JSON.stringify(outdatedSchemaVersions)} as const

export const defaultGrapherConfig = ${JSON.stringify(defaultConfig, undefined, 2)} as GrapherInterface
`
    const formatted = await format(
        "defaultGrapherConfig.ts",
        source,
        oxfmtConfig as FormatConfig
    )
    return formatted.code
}

export function formatSchemaFileName(
    version: string,
    revision?: number
): string {
    if (revision === undefined) return `grapher-schema.${version}.json`
    return `grapher-schema.${version}.${String(revision).padStart(2, "0")}.json`
}

const revisionedSchemaFilePattern =
    /^grapher-schema\.(?<version>\d+)\.(?<revision>\d{2})\.json$/

/** The inverse of `formatSchemaFileName`'s revisioned form */
export function parseSchemaFileRevision(
    fileName: string,
    version: string
): number | undefined {
    const groups = fileName.match(revisionedSchemaFilePattern)?.groups
    if (groups?.version !== version) return undefined
    return Number(groups.revision)
}

export function findHighestPublishedRevision(
    fileNames: string[],
    version: string
): number | undefined {
    return _.max(
        fileNames
            .map((fileName) => parseSchemaFileRevision(fileName, version))
            .filter((revision) => revision !== undefined)
    )
}

export function chooseSchemaRevision(
    builtJson: string,
    published: { revision: number; json: string } | undefined
): SchemaRevisionDecision {
    if (published === undefined) return { revision: 0, isChanged: true }
    if (published.json === builtJson)
        return { revision: published.revision, isChanged: false }
    return { revision: published.revision + 1, isChanged: true }
}

export function serializeJson(value: unknown): string {
    return `${JSON.stringify(value, null, 2)}\n`
}
