import * as _ from "lodash-es"
import type { JSONSchema7 } from "json-schema"
import { format, type FormatConfig } from "oxfmt"
import oxfmtConfig from "../../.oxfmtrc.json"
import { type SchemaDefinitions, resolveRef } from "./grapherSchemaSource.js"

export type SchemaArtefactSuffix = "json" | "layer.json"

/** The full schema with only `$schema` required */
export function toLayerSchema(schema: JSONSchema7): JSONSchema7 {
    if (!schema.$id?.endsWith(".json"))
        throw new Error(
            `Expected $id to end in ".json", got ${JSON.stringify(schema.$id)}`
        )

    const layer = structuredClone(schema)
    layer.required = ["$schema"]
    layer.$id = schema.$id.replace(/\.json$/, ".layer.json")
    return layer
}

/** Every `default` in the schema as one nested object */
export function generateDefaultConfig(
    schema: JSONSchema7,
    defs: SchemaDefinitions
): Record<string, unknown> {
    const defaultObject: Record<string, unknown> = {}
    if (schema.type !== "object") return defaultObject

    for (const [key, rawProperty] of Object.entries(schema.properties ?? {})) {
        const property = resolveRef(rawProperty, defs)
        if (property.type === "object") {
            const defaults = generateDefaultConfig(property, defs)
            if (Object.keys(defaults).length > 0) defaultObject[key] = defaults
        } else if (
            property.default !== undefined &&
            property.default !== null
        ) {
            defaultObject[key] = property.default
        }
    }
    return defaultObject
}

export async function renderDefaultConfigFile(
    version: string,
    defaultConfig: Record<string, unknown>
): Promise<string> {
    const outdatedSchemaVersions = _.range(1, Number(version)).map(
        (outdatedVersion) => String(outdatedVersion).padStart(3, "0")
    )

    const source = `// THIS IS A GENERATED FILE, DO NOT EDIT DIRECTLY

// GENERATED BY devTools/schema/buildGrapherSchema.ts

import { GrapherInterface } from "@ourworldindata/types"

export const latestSchemaVersion = "${version}" as const
export const outdatedSchemaVersions = ${JSON.stringify(outdatedSchemaVersions)} as const

export const defaultGrapherConfig = ${JSON.stringify(defaultConfig, undefined, 2)} as GrapherInterface
`
    const formatted = await format(
        "defaultGrapherConfig.ts",
        source,
        oxfmtConfig as FormatConfig
    )
    return formatted.code
}

export function formatSchemaFileName(
    version: string,
    suffix: SchemaArtefactSuffix
): string {
    return `grapher-schema.${version}.${suffix}`
}

export interface SchemaArtefact {
    fileName: string
    content: string
}

export function buildSchemaArtefact(
    version: string,
    suffix: SchemaArtefactSuffix,
    content: string
): SchemaArtefact {
    return { fileName: formatSchemaFileName(version, suffix), content }
}

export function serializeJson(value: unknown): string {
    return `${JSON.stringify(value, null, 2)}\n`
}
