name: Bespoke

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

defaults:
  run:
    working-directory: bespoke

jobs:
  bespoke-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-node-yarn-deps
        with:
          runPostinstallScripts: false
          cacheDependencyPath: bespoke/yarn.lock

      - name: Install bespoke dependencies
        run: yarn --immutable

      - name: Typecheck
        run: yarn typecheck

  bespoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-node-yarn-deps
        with:
          runPostinstallScripts: false
          cacheDependencyPath: bespoke/yarn.lock

      - name: Install bespoke dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test

  bespoke-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-node-yarn-deps
        with:
          runPostinstallScripts: false
          cacheDependencyPath: bespoke/yarn.lock

      - name: Install bespoke dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build
