name: Buildkite

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  destroy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          python .github/scripts/buildkite_destroy_staging.py
