name: PR Todo Checker

on:
  pull_request_review_comment:
    types: [edited, deleted]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  find_todos:
    runs-on: ubuntu-latest
    # don't run on draft PRs
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check for Todos
        uses: phntmxyz/pr_todo_checker@ca2891552a6cd4069c6afb83c955133e77dac685 # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
